### ISSUE TITLE
Insight into aborted run

### ISSUE THREAD

**Issue by juefish** [chanzuckerberg/shasta#117]
During a recent assembly of prokaryotic MinION data on Shasta v0.4.0, using the following code:

shasta --command=assemble --memoryBacking 2M --threads 8 --input ../../data/Diaz11.ONT.fasta --assemblyDirectory Diaz11_shastaV2 > shasta.log 

Got the following error:

terminate called after throwing an instance of 'std::runtime_error'
  what():  Error unmapping.
Aborted

However, log file reported this at the end:
Using 8 threads.
Assembly begins for 2 edges of the assembly graph.
2020-Apr-16 22:48:03.540986 Assembled a total 6907818 bases for 2 assembly graph edges of which 1 where assembled.
The assembly graph has 2 vertices and 2 edges of which 1 were assembled.
Total length of assembled sequence is 6907818
N50 for assembly segments is 6907818
...
2020-Apr-16 22:48:03.545419 writeGfa1 begins
2020-Apr-16 22:48:03.911467 writeGfa1 ends
2020-Apr-16 22:48:03.915309 writeGfa1BothStrands begins
2020-Apr-16 22:48:04.596424 writeGfa1BothStrands ends
2020-Apr-16 22:48:04.600124 writeFasta begins
2020-Apr-16 22:48:04.962609 writeFasta ends
Assembly time statistics:
    Elapsed seconds: 648.023
    Elapsed minutes: 10.8004
    Elapsed hours:   0.180006
Average CPU utilization: 0.211944
Shasta Release 0.4.0

Did this run abort before finishing or run to completion?

**Comment by paoloczi** [comment]
This assembly completed and was in its final phases before termination, mostly releasing allocated memory. An error occurred while releasing one of the memory areas on 2 MB pages used during the assembly. It is hard to tell what the error was, but it is probably system related. I will add more information to that error message, so if it occurs again we will have a better idea of what happened.

However, the output of your assembly was not affected, should have been properly closed, and should be intact on disk.

**Comment by juefish** [comment]
Thanks. Let me know if there's any information I can send you or if there's a run I can do to help resolve the issue. Happy to help if I can.

**Comment by paoloczi** [comment]
Thank you. Without more information from the message, there is nothing else that I can do. I added yesterday a more extensive message that includes a description of the error. That will be in the next release, and with that if this happens again to you or anybody else we will have a better idea.
