### ISSUE TITLE
Empty assembly fasta file

### ISSUE THREAD

**Issue by EvoEpi** [chanzuckerberg/shasta#130]
Hi,

I am running shasta 0.4.0, but with limited success. My "successful" runs produce an empty Assembly.fasta. I am running shasta as follows:

```bash
/shasta-Linux-0.4.0 \
--input seq.fasta \
--threads 32 \
--Kmers.k 15 \
--Kmers.probability 0.02 \
--MinHash.m 12 \
--MinHash.minBucketSize 20 \
--MinHash.maxBucketSize 100 \
--MinHash.minHashIterationCount 25 \
--MinHash.minFrequency 10 \
--Align.minAlignedMarkerCount 50 \
--ReadGraph.maxAlignmentCount 20 \
--Assembly.consensusCaller Modal \
--memoryMode filesystem \
--memoryBacking disk
```

I am setting `--memoryMode filesystem` and `--memoryBacking disk` because of other errors associated with (what I am assuming) is root privileges on the cloud. I have also tried `--memoryMode anonymous` and `--memoryBacking 4K`, but these executions fail.

Thoughts?

Thanks!

**Comment by paoloczi** [comment]
It is likely that this assembly did not find enough alignments between reads. What type of reads are you using? The options you are using seem suited to high accuracy reads. 

Please attach the following so I can get a better idea of what is going on:

- The entire log output (stdout).
- `AssemblySummary.html`
- `LowHashBucketHistogram.csv`

It would also help me to know the expected size of the genome you are assembling.

Regarding memory options, if you don't have root access the easiest is to use the default options `--memoryMode anonymous --memoryBacking 4K`. Those would be give you better performance than the options you are using, but would not affect assembly results.

**Comment by EvoEpi** [comment]
Thanks for the speedy reply!

I am using Sequel I reads. What suggestions do you have for this type of long read data?

Yep, number of good alignments is 0.

Files: [Archive.zip](https://github.com/chanzuckerberg/shasta/files/4630528/Archive.zip)

Genome size is ~2.4 Gbp.

**Comment by paoloczi** [comment]
I spent just a small amount of time a few months ago experimenting with different types of PacBio reads and I got decent assemblies, but more work is needed to squeeze the best out these reads. Among the sample Shasta configuration files in `shasta/conf`, the ones that may be useful to you are  `shasta/conf/PacBio-CCS-Dec2019.conf` and `shasta/conf/PacBio-CLR-Dec2019.conf`. To pass a configuration file to Shasta, use `--conf /absolutePathToConfigFile`. 

However those configuration files are just starting points and I don't necessarily expect that they will work well in your case. Some tuning of assembly parameters is probably needed.

From the html summary you posted, I see that the number of alignment candidates found by the MinHash algorithm is essentially zero. This means that we have to start by tuning MinHash parameters. Looking at the histogram file you posted, I suspect `--MinHash.m 20` may be excessive (the configuration files I mentioned above use 12 and 4 respectively). This controls the number of consecutive aligned markers that define a feature for the purposes of the MinHash/LowHash algorithm. You are asking for 20 consecutive aligned markers of 15 RLE bases each. This is probably too much even for highly accurate reads. 

To get an idea of how marker alignments look for your data, you could use the Shasta http server. If you look at issue #128, just today I wrote some detailed directions for using the Shasta http server to study alignments. I suggest that you do that. Even after an unsuccessful assembly, you can run the http server and use the "Align one read with all" functionality to study marker alignments for your reads. That will help you tune both MinHash/LowHash and alignment parameters.

You have only 28 Gb of coverage, which is coverage 12x for your genome. This is on the low side. Once MinHash and alignment parameters are fixed, you will probably also need to reduce `--MarkerGraph.minCoverage` from the default 10 to 5. For nanopore data I have never been able to get a good assembly at such low coverage, but things might be different for your reads.

**Comment by paoloczi** [comment]
Based on what I am hearing from my colleagues about this sequencing platform, it is likely that `shasta/conf/PacBio-CLR-Dec2019.conf` is closer to what you need than the other one. You could start with that, adding `MarkerGraph.minCoverage 5` to account for low coverage, and with `--memoryMode filesystem --memoryBacking disk` so you can then use the Shasta http server to look at alignments.

**Comment by EvoEpi** [comment]
Awesome! I will take all of this and run with it. Thank you so much!

One more thing, in the config file `PacBio-CLR-Dec2019.conf`, one flag is given as `maxAlignmentCount`, is this equivalent to `ReadGraph.maxAlignmentCount`?

**Comment by paoloczi** [comment]
The configuration file consists of sections, each introduced by a name in square brackets. So for example, command line option `--ReadGraph.maxAlignmentCount 6` can instead be specified with a line `maxAlignmentCount = 6` in the `[ReadGraph]` section. See [here](https://chanzuckerberg.github.io/shasta/CommandLineOptions.html#ConfigFile) for more information about using configuration files in Shasta.

**Comment by EvoEpi** [comment]
Thanks, again! ONE more questions, what if my PacBio Sequel I coverage is around 20-30X. Any recommendations for parameter settings?

**Comment by paoloczi** [comment]
I would reduce `--MarkerGraph.minCoverage` from the default 10 to 5 and see what happens. If you don't get a successful assembly let me know and I can help diagnose and tune parameters.

**Comment by EvoEpi** [comment]
Sounds like a plan! Thank you again!

**Comment by paoloczi** [comment]
I will close this issue, but feel free to create a new one if you still cannot obtain a satisfactory assembly.
