### ISSUE TITLE
Error with --memoryBacking 2M 

### ISSUE THREAD

**Issue by soumyarao86** [chanzuckerberg/shasta#140]
Hi,

I assembled mouse data (3 .fq files of ~ 1GB) using Shasta on docker with --memoryBacking 4K.
However I am getting an error when I try running it with --memoryBacking 2M.  
I have ~1 TB of disc space. 

sh: 1: cannot create /sys/kernel/mm/hugepages/hugepages-2048kB/nr_overcommit_hugepages: Read-only file system
2020-Jun-04 03:07:07.694208 Terminated after catching a runtime error exception:
Error 512: Unknown error 512 running command: sudo sh -c "echo 382823 > /sys/kernel/mm/hugepages/hugepages-2048kB/nr_overcommit_hugepages"
Command exited with non-zero status 2

[RBP4_KO_suzukiEtal2020_shasta-suzuki2.log](https://github.com/chanzuckerberg/shasta/files/4727306/RBP4_KO_suzukiEtal2020_shasta-suzuki2.log)

**Comment by bagashe** [comment]
Hi @soumyarao86 - Could you share the entire command you used? You typically need root privilege in order to use the `--memoryBacking 2M` option. https://chanzuckerberg.github.io/shasta/Performance.html has some details.

**Comment by soumyarao86** [comment]
Hi @bagashe, I got similar error while running on a system with root privilege with the following command:
$ sudo docker run -v `pwd`:/data kishwars/shasta:latest --input sra_data2.fasta sra_data1.fasta sr                              a_data.fasta --assemblyDirectory shasta_sra_suzukiEtal2020 --command assemble --threads 32 --memoryBacking 2M

Error:
sh: 1: cannot create /sys/kernel/mm/hugepages/hugepages-2048kB/nr_overcommit_hugepages: Read-only file system
2020-Jun-04 02:27:27.712608 Terminated after catching a runtime error exception:
Error 512: Unknown error 512 running command: sudo sh -c "echo 27999 > /sys/kernel/mm/hugepages/hugepages-2048kB/nr_overcommit_                              hugepages"
Command exited with non-zero status 2

DEBUG_MAX_MEM:4960

**Comment by soumyarao86** [comment]
I tried the same command on google cloud console and had the same error. Does it have to do anything with docker run?

**Comment by paoloczi** [comment]
I am not a Docker expert but I will ask some of my colleagues to pitch in. I know that Docker supports 2MB pages, but you may have to do something to enable them.

In the meantime, as a workaround you could try the default options `--memoryMode anonymous --memoryBacking 4K` or, if you want to save binary data to use the http server or the Python API, `--memoryMode filesystem --memoryBacking disk`.

**Comment by paoloczi** [comment]
According to the [Shasta Docker documentation](https://chanzuckerberg.github.io/shasta/Docker.html), to use 2MB pages you must use Docker option `--privileged`. Here is the example from the documentation:

```
docker run --privileged -v `pwd`:/data kishwars/shasta:latest --input input.fasta --memoryMode filesystem --memoryBacking 2M
```

**Comment by soumyarao86** [comment]
Thanks @paoloczi, it worked!
