### ISSUE TITLE
assembly parameters for low depth of coverage

### ISSUE THREAD

**Issue by zhenzhenyang-psu** [chanzuckerberg/shasta#156]
Hi Chan,
I know the desired depth of coverage is 60, but in my case, I have nanopore reads of only 10x coverage.
For desired output, is there any parameters that I shall change for a successful run?

Also, i have another issue regarding the support system for shasta.
The server for which I have large RAM nodes is a centOS6, which complained about errors like "kernel too old, core dumped". When I switched to a centOS7 node, this error was avoided. However, I didn't have large fat nodes on that system. Do you have any suggestions?

thanks much,
zhenzhen

**Comment by paoloczi** [comment]
To use Shasta on a Linux system with an old kernel, download [shasta-OldLinux-0.5.0](https://github.com/chanzuckerberg/shasta/releases/download/0.5.0/shasta-OldLinux-0.5.0). Please let us know if you still have a problem with that on CentOS 6.

At coverage 10x it is going to be hard to achieve a good assembly.We have not had the time to optimize assembly parameters for low coverage, but there is some discussion of that in issue #7. In particular, here is a list of assembly parameters that should probably be reduced proportionally to coverage:

```
MinHash.maxBucketSize
MarkerGraph.minCoverage
MarkerGraph.maxCoverage
MarkerGraph.lowCoverageThreshold
MarkerGraph.highCoverageThreshold
MarkerGraph.edgeMarkerSkipThreshold
```

However, I would be surprised if you were able to obtain a good assembly at coverage 10x. But good luck!

**Comment by zhenzhenyang-psu** [comment]
I actually tried shasta-OldLinux-0.5.0, yet it still reported errors like "kernel too old". I am trying to build from source and see if it works.

While I was trying to build from source, there was an error while compiling package spoa, 
error message occurred while I typed "make -j all":

Scanning dependencies of target spoa
[ 20%] Building CXX object CMakeFiles/spoa.dir/src/alignment_engine.cpp.o
[ 40%] Building CXX object CMakeFiles/spoa.dir/src/dispatcher.cpp.o
[ 60%] Building CXX object CMakeFiles/spoa.dir/src/graph.cpp.o
[ 80%] Building CXX object CMakeFiles/spoa.dir/src/sisd_alignment_engine.cpp.o
In file included from /tmp/shasta-build.bY1y/spoa-v3.4.0/src/sisd_alignment_engine.hpp:14,
                 from /tmp/shasta-build.bY1y/spoa-v3.4.0/src/alignment_engine.cpp:12:
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/alignment_engine.hpp:30: error: expected nested-name-specifier before 'Alignment'
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/alignment_engine.hpp:30: error: 'Alignment' has not been declared
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/alignment_engine.hpp:30: error: expected ';' before '=' token
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/alignment_engine.hpp:30: error: expected unqualified-id before '=' token
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/alignment_engine.hpp:50: error: 'Alignment' does not name a type
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/alignment_engine.hpp:53: error: 'Alignment' does not name a type
In file included from /tmp/shasta-build.bY1y/spoa-v3.4.0/src/alignment_engine.cpp:12:
/tmp/shasta-build.bY1y/spoa-v3.4.0/src/sisd_alignment_engine.hpp:30: error: expected ';' before 'override'
/tmp/shasta-build.bY1y/spoa-v3.4.0/src/sisd_alignment_engine.hpp:32: error: 'Alignment' does not name a type
/tmp/shasta-build.bY1y/spoa-v3.4.0/src/sisd_alignment_engine.hpp:47: error: 'Alignment' does not name a type
/tmp/shasta-build.bY1y/spoa-v3.4.0/src/sisd_alignment_engine.hpp:50: error: 'Alignment' does not name a type
/tmp/shasta-build.bY1y/spoa-v3.4.0/src/sisd_alignment_engine.hpp:53: error: 'Alignment' does not name a type
/tmp/shasta-build.bY1y/spoa-v3.4.0/src/sisd_alignment_engine.hpp:60: error: expected ';' before 'noexcept'
In file included from /tmp/shasta-build.bY1y/spoa-v3.4.0/src/alignment_engine.cpp:13:
/tmp/shasta-build.bY1y/spoa-v3.4.0/src/simd_alignment_engine.hpp:43: error: expected ';' before 'override'
/tmp/shasta-build.bY1y/spoa-v3.4.0/src/simd_alignment_engine.hpp:45: error: 'Alignment' does not name a type
/tmp/shasta-build.bY1y/spoa-v3.4.0/src/simd_alignment_engine.hpp:61: error: expected constructor, destructor, or type conversion before 'linear'
/tmp/shasta-build.bY1y/spoa-v3.4.0/src/simd_alignment_engine.hpp:65: error: expected constructor, destructor, or type conversion before 'affine'
/tmp/shasta-build.bY1y/spoa-v3.4.0/src/simd_alignment_engine.hpp:69: error: expected constructor, destructor, or type conversion before 'convex'
/tmp/shasta-build.bY1y/spoa-v3.4.0/src/simd_alignment_engine.hpp:78: error: expected initializer before 'noexcept'
/tmp/shasta-build.bY1y/spoa-v3.4.0/src/alignment_engine.cpp: In function 'std::unique_ptr<spoa::AlignmentEngine, std::default_delete<spoa::AlignmentEngine> > spoa::createAlignmentEngine(spoa::AlignmentType, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t)':
/tmp/shasta-build.bY1y/spoa-v3.4.0/src/alignment_engine.cpp:64: error: 'nullptr' was not declared in this scope
/tmp/shasta-build.bY1y/spoa-v3.4.0/src/alignment_engine.cpp: At global scope:
/tmp/shasta-build.bY1y/spoa-v3.4.0/src/alignment_engine.cpp:77: error: 'Alignment' does not name a type
make[2]: *** [CMakeFiles/spoa.dir/src/alignment_engine.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /tmp/shasta-build.bY1y/spoa-v3.4.0/src/sisd_alignment_engine.cpp:10:
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:24: error: expected nested-name-specifier before 'Alignment'
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:24: error: 'Alignment' has not been declared
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:24: error: expected ';' before '=' token
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:24: error: expected unqualified-id before '=' token
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:50: error: ISO C++ forbids declaration of 'Alignment' with no type
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:50: error: expected ',' or '...' before '&' token
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:53: error: ISO C++ forbids declaration of 'Alignment' with no type
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:53: error: expected ',' or '...' before '&' token
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:53: error: 'void spoa::Graph::add_alignment(int)' cannot be overloaded
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:50: error: with 'void spoa::Graph::add_alignment(int)'
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:56: error: ISO C++ forbids declaration of 'Alignment' with no type
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:56: error: expected ',' or '...' before '&' token
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:56: error: 'void spoa::Graph::add_alignment(int)' cannot be overloaded
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:50: error: with 'void spoa::Graph::add_alignment(int)'
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:59: error: ISO C++ forbids declaration of 'Alignment' with no type
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:59: error: expected ',' or '...' before '&' token
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:59: error: 'void spoa::Graph::add_alignment(int)' cannot be overloaded
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:50: error: with 'void spoa::Graph::add_alignment(int)'
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:63: error: ISO C++ forbids declaration of 'Alignment' with no type
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:63: error: expected ',' or '...' before '&' token
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:63: error: 'void spoa::Graph::add_alignment(int)' cannot be overloaded
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:50: error: with 'void spoa::Graph::add_alignment(int)'
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:66: error: ISO C++ forbids declaration of 'Alignment' with no type
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:66: error: expected ',' or '...' before '&' token
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:66: error: 'void spoa::Graph::add_alignment(int)' cannot be overloaded
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:50: error: with 'void spoa::Graph::add_alignment(int)'
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:81: error: 'Alignment' has not been declared
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:165: error: a class-key must be used when declaring a friend
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:165: error: friend declaration does not name a class or function
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:191: error: a class-key must be used when declaring a friend
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:191: error: friend declaration does not name a class or function
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:192: error: a class-key must be used when declaring a friend
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:192: error: friend declaration does not name a class or function
In file included from /tmp/shasta-build.bY1y/spoa-v3.4.0/src/sisd_alignment_engine.hpp:14,
                 from /tmp/shasta-build.bY1y/spoa-v3.4.0/src/sisd_alignment_engine.cpp:11:
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/alignment_engine.hpp:30: error: expected nested-name-specifier before 'Alignment'
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/alignment_engine.hpp:30: error: 'Alignment' has not been declared
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/alignment_engine.hpp:30: error: expected ';' before '=' token
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/alignment_engine.hpp:30: error: expected unqualified-id before '=' token
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/alignment_engine.hpp:50: error: 'Alignment' does not name a type
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/alignment_engine.hpp:53: error: 'Alignment' does not name a type
In file included from /tmp/shasta-build.bY1y/spoa-v3.4.0/src/sisd_alignment_engine.cpp:11:
/tmp/shasta-build.bY1y/spoa-v3.4.0/src/sisd_alignment_engine.hpp:30: error: expected ';' before 'override'
/tmp/shasta-build.bY1y/spoa-v3.4.0/src/sisd_alignment_engine.hpp:32: error: 'Alignment' does not name a type
/tmp/shasta-build.bY1y/spoa-v3.4.0/src/sisd_alignment_engine.hpp:47: error: 'Alignment' does not name a type
/tmp/shasta-build.bY1y/spoa-v3.4.0/src/sisd_alignment_engine.hpp:50: error: 'Alignment' does not name a type
/tmp/shasta-build.bY1y/spoa-v3.4.0/src/sisd_alignment_engine.hpp:53: error: 'Alignment' does not name a type
/tmp/shasta-build.bY1y/spoa-v3.4.0/src/sisd_alignment_engine.hpp:60: error: expected ';' before 'noexcept'
/tmp/shasta-build.bY1y/spoa-v3.4.0/src/sisd_alignment_engine.cpp:15: error: 'constexpr' does not name a type
/tmp/shasta-build.bY1y/spoa-v3.4.0/src/sisd_alignment_engine.cpp: In function 'std::unique_ptr<spoa::AlignmentEngine, std::default_delete<spoa::AlignmentEngine> > spoa::createSisdAlignmentEngine(spoa::AlignmentType, spoa::AlignmentSubtype, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t)':
/tmp/shasta-build.bY1y/spoa-v3.4.0/src/sisd_alignment_engine.cpp:23: error: cannot allocate an object of abstract type 'spoa::SisdAlignmentEngine'
/tmp/shasta-build.bY1y/spoa-v3.4.0/src/sisd_alignment_engine.hpp:25: note:   because the following virtual functions are pure within 'spoa::SisdAlignmentEngine':
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/alignment_engine.hpp:47: note: 	virtual void spoa::AlignmentEngine::prealloc(uint32_t, uint32_t)
/tmp/shasta-build.bY1y/spoa-v3.4.0/src/sisd_alignment_engine.cpp: In constructor 'spoa::SisdAlignmentEngine::Implementation::Implementation()':
/tmp/shasta-build.bY1y/spoa-v3.4.0/src/sisd_alignment_engine.cpp:37: error: 'nullptr' was not declared in this scope
/tmp/shasta-build.bY1y/spoa-v3.4.0/src/sisd_alignment_engine.cpp: At global scope:
/tmp/shasta-build.bY1y/spoa-v3.4.0/src/sisd_alignment_engine.cpp:53: error: no 'void spoa::SisdAlignmentEngine::prealloc(uint32_t, uint32_t)' member function declared in class 'spoa::SisdAlignmentEngine'
/tmp/shasta-build.bY1y/spoa-v3.4.0/src/sisd_alignment_engine.cpp: In member function 'void spoa::SisdAlignmentEngine::realloc(uint32_t, uint32_t, uint32_t)':
/tmp/shasta-build.bY1y/spoa-v3.4.0/src/sisd_alignment_engine.cpp:72: error: 'nullptr' was not declared in this scope
/tmp/shasta-build.bY1y/spoa-v3.4.0/src/sisd_alignment_engine.cpp: At global scope:
/tmp/shasta-build.bY1y/spoa-v3.4.0/src/sisd_alignment_engine.cpp:95: error: expected initializer before 'noexcept'
/tmp/shasta-build.bY1y/spoa-v3.4.0/src/sisd_alignment_engine.cpp:912: error: expected '}' at end of input
make[2]: *** [CMakeFiles/spoa.dir/src/sisd_alignment_engine.cpp.o] Error 1
In file included from /tmp/shasta-build.bY1y/spoa-v3.4.0/src/graph.cpp:13:
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:24: error: expected nested-name-specifier before 'Alignment'
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:24: error: 'Alignment' has not been declared
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:24: error: expected ';' before '=' token
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:24: error: expected unqualified-id before '=' token
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:50: error: ISO C++ forbids declaration of 'Alignment' with no type
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:50: error: expected ',' or '...' before '&' token
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:53: error: ISO C++ forbids declaration of 'Alignment' with no type
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:53: error: expected ',' or '...' before '&' token
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:53: error: 'void spoa::Graph::add_alignment(int)' cannot be overloaded
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:50: error: with 'void spoa::Graph::add_alignment(int)'
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:56: error: ISO C++ forbids declaration of 'Alignment' with no type
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:56: error: expected ',' or '...' before '&' token
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:56: error: 'void spoa::Graph::add_alignment(int)' cannot be overloaded
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:50: error: with 'void spoa::Graph::add_alignment(int)'
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:59: error: ISO C++ forbids declaration of 'Alignment' with no type
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:59: error: expected ',' or '...' before '&' token
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:59: error: 'void spoa::Graph::add_alignment(int)' cannot be overloaded
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:50: error: with 'void spoa::Graph::add_alignment(int)'
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:63: error: ISO C++ forbids declaration of 'Alignment' with no type
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:63: error: expected ',' or '...' before '&' token
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:63: error: 'void spoa::Graph::add_alignment(int)' cannot be overloaded
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:50: error: with 'void spoa::Graph::add_alignment(int)'
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:66: error: ISO C++ forbids declaration of 'Alignment' with no type
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:66: error: expected ',' or '...' before '&' token
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:66: error: 'void spoa::Graph::add_alignment(int)' cannot be overloaded
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:50: error: with 'void spoa::Graph::add_alignment(int)'
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:81: error: 'Alignment' has not been declared
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:165: error: a class-key must be used when declaring a friend
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:165: error: friend declaration does not name a class or function
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:191: error: a class-key must be used when declaring a friend
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:191: error: friend declaration does not name a class or function
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:192: error: a class-key must be used when declaring a friend
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:192: error: friend declaration does not name a class or function
/tmp/shasta-build.bY1y/spoa-v3.4.0/src/graph.cpp:17: error: 'constexpr' does not name a type
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp: In static member function 'static std::unique_ptr<spoa::Node, std::default_delete<spoa::Node> > spoa::Graph::createNode(uint32_t, uint32_t)':
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:168: error: 'spoa::Node::Node(uint32_t, uint32_t)' is private
/tmp/shasta-build.bY1y/spoa-v3.4.0/src/graph.cpp:20: error: within this context
/tmp/shasta-build.bY1y/spoa-v3.4.0/src/graph.cpp: In member function 'bool spoa::Node::successor(uint32_t&, uint32_t) const':
/tmp/shasta-build.bY1y/spoa-v3.4.0/src/graph.cpp:33: error: expected initializer before ':' token
/tmp/shasta-build.bY1y/spoa-v3.4.0/src/graph.cpp:791: error: expected primary-expression at end of input
/tmp/shasta-build.bY1y/spoa-v3.4.0/src/graph.cpp:791: error: expected ';' at end of input
/tmp/shasta-build.bY1y/spoa-v3.4.0/src/graph.cpp:791: error: expected primary-expression at end of input
/tmp/shasta-build.bY1y/spoa-v3.4.0/src/graph.cpp:791: error: expected ')' at end of input
/tmp/shasta-build.bY1y/spoa-v3.4.0/src/graph.cpp:791: error: expected statement at end of input
/tmp/shasta-build.bY1y/spoa-v3.4.0/src/graph.cpp:791: error: expected '}' at end of input
/tmp/shasta-build.bY1y/spoa-v3.4.0/src/graph.cpp:791: warning: no return statement in function returning non-void
/tmp/shasta-build.bY1y/spoa-v3.4.0/src/graph.cpp: At global scope:
/tmp/shasta-build.bY1y/spoa-v3.4.0/src/graph.cpp:31: warning: unused parameter 'dst'
/tmp/shasta-build.bY1y/spoa-v3.4.0/src/graph.cpp:31: warning: unused parameter 'label'
/tmp/shasta-build.bY1y/spoa-v3.4.0/src/graph.cpp:791: error: expected '}' at end of input
make[2]: *** [CMakeFiles/spoa.dir/src/graph.cpp.o] Error 1
In file included from /tmp/shasta-build.bY1y/spoa-v3.4.0/src/simd_alignment_engine_impl.hpp:24,
                 from /tmp/shasta-build.bY1y/spoa-v3.4.0/src/dispatcher.cpp:7:
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:24: error: expected nested-name-specifier before 'Alignment'
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:24: error: 'Alignment' has not been declared
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:24: error: expected ';' before '=' token
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:24: error: expected unqualified-id before '=' token
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:50: error: ISO C++ forbids declaration of 'Alignment' with no type
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:50: error: expected ',' or '...' before '&' token
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:53: error: ISO C++ forbids declaration of 'Alignment' with no type
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:53: error: expected ',' or '...' before '&' token
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:53: error: 'void spoa::Graph::add_alignment(int)' cannot be overloaded
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:50: error: with 'void spoa::Graph::add_alignment(int)'
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:56: error: ISO C++ forbids declaration of 'Alignment' with no type
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:56: error: expected ',' or '...' before '&' token
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:56: error: 'void spoa::Graph::add_alignment(int)' cannot be overloaded
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:50: error: with 'void spoa::Graph::add_alignment(int)'
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:59: error: ISO C++ forbids declaration of 'Alignment' with no type
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:59: error: expected ',' or '...' before '&' token
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:59: error: 'void spoa::Graph::add_alignment(int)' cannot be overloaded
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:50: error: with 'void spoa::Graph::add_alignment(int)'
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:63: error: ISO C++ forbids declaration of 'Alignment' with no type
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:63: error: expected ',' or '...' before '&' token
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:63: error: 'void spoa::Graph::add_alignment(int)' cannot be overloaded
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:50: error: with 'void spoa::Graph::add_alignment(int)'
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:66: error: ISO C++ forbids declaration of 'Alignment' with no type
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:66: error: expected ',' or '...' before '&' token
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:66: error: 'void spoa::Graph::add_alignment(int)' cannot be overloaded
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:50: error: with 'void spoa::Graph::add_alignment(int)'
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:81: error: 'Alignment' has not been declared
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:165: error: a class-key must be used when declaring a friend
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:165: error: friend declaration does not name a class or function
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:191: error: a class-key must be used when declaring a friend
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:191: error: friend declaration does not name a class or function
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:192: error: a class-key must be used when declaring a friend
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/graph.hpp:192: error: friend declaration does not name a class or function
In file included from /tmp/shasta-build.bY1y/spoa-v3.4.0/src/simd_alignment_engine.hpp:14,
                 from /tmp/shasta-build.bY1y/spoa-v3.4.0/src/simd_alignment_engine_impl.hpp:25,
                 from /tmp/shasta-build.bY1y/spoa-v3.4.0/src/dispatcher.cpp:7:
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/alignment_engine.hpp:30: error: expected nested-name-specifier before 'Alignment'
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/alignment_engine.hpp:30: error: 'Alignment' has not been declared
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/alignment_engine.hpp:30: error: expected ';' before '=' token
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/alignment_engine.hpp:30: error: expected unqualified-id before '=' token
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/alignment_engine.hpp:50: error: 'Alignment' does not name a type
/tmp/shasta-build.bY1y/spoa-v3.4.0/include/spoa/alignment_engine.hpp:53: error: 'Alignment' does not name a type
In file included from /tmp/shasta-build.bY1y/spoa-v3.4.0/src/simd_alignment_engine_impl.hpp:25,
                 from /tmp/shasta-build.bY1y/spoa-v3.4.0/src/dispatcher.cpp:7:
/tmp/shasta-build.bY1y/spoa-v3.4.0/src/simd_alignment_engine.hpp:43: error: expected ';' before 'override'
/tmp/shasta-build.bY1y/spoa-v3.4.0/src/simd_alignment_engine.hpp:45: error: 'Alignment' does not name a type
/tmp/shasta-build.bY1y/spoa-v3.4.0/src/simd_alignment_engine.hpp:61: error: expected constructor, destructor, or type conversion before 'linear'
/tmp/shasta-build.bY1y/spoa-v3.4.0/src/simd_alignment_engine.hpp:65: error: expected constructor, destructor, or type conversion before 'affine'
/tmp/shasta-build.bY1y/spoa-v3.4.0/src/simd_alignment_engine.hpp:69: error: expected constructor, destructor, or type conversion before 'convex'
/tmp/shasta-build.bY1y/spoa-v3.4.0/src/simd_alignment_engine.hpp:78: error: expected initializer before 'noexcept'
In file included from /tmp/shasta-build.bY1y/spoa-v3.4.0/src/dispatcher.cpp:7:
/tmp/shasta-build.bY1y/spoa-v3.4.0/src/simd_alignment_engine_impl.hpp:32: error: expected initializer before 'noexcept'
/tmp/shasta-build.bY1y/spoa-v3.4.0/src/dispatcher.cpp:61: error: expected '}' at end of input
make[2]: *** [CMakeFiles/spoa.dir/src/dispatcher.cpp.o] Error 1
make[1]: *** [CMakeFiles/spoa.dir/all] Error 2
make: *** [all] Error 2

Do you happen to know how to fix this compiliationi error?
By the way, I will try the low depth parameters, thanks much,
zhenzhen

**Comment by zhenzhenyang-psu** [comment]
Hi, 
sorry for the long error message. It was fixed with newer version of gcc and g++ and pass it to cmake. the following commands worked for me in the end:

module load apps/cmake/3.7.0-rc3
module load compiler/gnu/5.5.0
module load apps/glib/2.14

cmake -DCMAKE_C_COMPILER=/public/software/compiler/gnu/5.5.0/bin/gcc -DCMAKE_CXX_COMPILER=/public/software/compiler/gnu/5.5.0/bin/g++  ../spoa-v3.4.0 -DBUILD_SHARED_LIBS=OFF

thanks,
zhenzhen

**Comment by paoloczi** [comment]
Regarding building Shasta on CentOS6 6, please see my comments on issue #157.
