### ISSUE TITLE
Shasta integration with snakemake

### ISSUE THREAD

**Issue by BCArg** [chanzuckerberg/shasta#172]
I have written a denovo assembly pipeline using snakemake where the first step is to build a draft assembly using shasta. Though I am wondering whether Shasta can be integrated into a snakemake pipeline at all.

The error that I am getting is that the output directory already existed prior to running shasta (I am getting the same error for all four samples I wanted to call the snakemake on)

```
2020-Jul-28 09:28:40.641060 Terminated after catching a runtime error exception:
Assembly directory BORDref248_barcode10/ShastaRun/ already exists.
Remove it or use --assemblyDirectory to specify a different assembly directory.
```

Those directories did not exist prior to calling snakemake, though they were specified in the the
1.  `output` directive of the `shasta` rule in the snakemake (please see below)
2. `--assemblyDirectory` flag in the `shell` directive of the shasta rule

as far as I am aware, the output directories as specified in `assemblyDirectory` were created by snakemake prior to executing the commands under `shell`. So given that shasta throws an error when the output directory already exists, I am now wondering if it can be integrated into a denovo assembly pipeline in snakemake at all.

Below  is the shasta rule:

```
rule shasta:
    input:
        fqdir + "{sample}.fastq"
    output:
        "{sample}/ShastaRun/Assembly.fasta",
        "{sample}/ShastaRun/Assembly.gfa",
        "{sample}/ShastaRun/Assembly-BothStrands.gfa",
        "{sample}/ShastaRun/shasta.conf",
        "{sample}/ShastaRun/ReadLengthHistogram.csv",
        "{sample}/ShastaRun/Binned-ReadLengthHistogram.csv",
        "{sample}/ShastaRun/PalindromicReads.csv",
        "{sample}/ShastaRun/ReadLowHashStatistics.csv",
        "{sample}/ShastaRun/LowHashBucketHistogram.csv",
        "{sample}/ShastaRun/ReadGraphComponents.csv",
        "{sample}/ShastaRun/MarkerGraphVertexCoverageHistogram.csv",
        "{sample}/ShastaRun/MarkerGraphEdgeCoverageHistogram.csv",
        "{sample}/ShastaRun/AssemblyGraphChainLengthHistogram.csv",
        "{sample}/ShastaRun/AssemblyGraph-Final.dot",
        "{sample}/ShastaRun/AssemblySummary.csv",
        "{sample}/ShastaRun/ReadSummary.csv",
        "{sample}/ShastaRun/index.html",
        "{sample}/ShastaRun/AssemblySummary.json",
        "{sample}/ShastaRun/AssemblySummary.html"
    shell:
        # "mkdir -p {wildcards.sample}/ShastaRun \n" # cannot do that, shasta will not work if the directory already exists!
        # the value passed to assemblyDirectory cannot be recursive, apparently
        "/home/bhinckel/downloads/shasta/shasta-Linux-0.5.1 --input {input} --assemblyDirectory {wildcards.sample}/ShastaRun/"
```

Which translated into the following shell command (example for one sample)

```
/home/bhinckel/downloads/shasta/shasta-Linux-0.5.1 --input /nexus/Gridion/20190905MicroRap/Microbio/20190905_1400_GA10000_FAK80986_effcd777/fastq_pass/demux/BORD1707_barcode02.fastq --assemblyDirectory BORD1707_barcode02/ShastaRun/
```

input file exists and permissions are appropriate (775)

**Comment by paoloczi** [comment]
The purpose of this behavior is to avoid overwriting a previous assembly if the user specifies by mistake an assembly directory that was run previously. 

To enable your application, we could change Shasta behavior to permit the assembly to proceed if the specified assembly directory already exists, but is empty. Is this the case for you? Can you verify that the assembly directory created by your system was empty when Shasta failed? If so, this modified behavior would satisfy your requirements, while still guaranteeing that nothing is ever overwritten. However, it would still not allow you to rerun an assembly in the same directory, without removing all the files in the assembly directory first. 

I would also caution you against an explicit list of Shasta output files. The list of output files can change depending on what assembly options were used, and will certainly change from release to release. Using an explicit list of output files will require continuous changes for practical use. If your tool requires a fixed list of files, I suggest considering a more flexible tool to implement your pipeline.

**Comment by BCArg** [comment]
Thanks very much for the quick response.

I can guarantee yes that the directory created when snakemake was called is indeed empty:

```
(base) bhinckel@Brightcore-testsrv:~/snakemake/ONTdeNovoAssembly$ tree out_shasta/
out_shasta/
└── 20190905MicroRap
    ├── BORD1705_barcode01
    │   └── ShastaRun
    ├── BORD1707_barcode02
    │   └── ShastaRun
    ├── BORD1717_barcode04
    │   └── ShastaRun
    └── BORDref248_barcode10
        └── ShastaRun
```

I do agree that specifying all the output files are not the most flexible option. Initially I tried to use `directory` option in the `output` directive of snakemake, but then I cannot use the output file from shasta (in this case `{sample}/ShastaRun/Assembly.fasta`) as input for the next rule. I wished yes that snakemake was more flexible in that regard.

So for my specific purpose (and for other snakemake users out there) it would certainly help a great deal if you, as you suggested, enable the option to proceed if the specified assembly directory already exists. 

At this point I just want to make sure that the pipeline works, Then I will explore the shasta parameters more in detail.

**Comment by paoloczi** [comment]
I will add this to our list of things to do, but I cannot promise how quickly it will be done. When this is done I will comment here, so at that point you can [download a test build](https://chanzuckerberg.github.io/shasta/BuildingFromSource.html#DownloadTestBuild) to continue your work, without having to wait for the next release.

Keep in mind this will still fail if the user attempts to run a second time on the same assembly directory.

**Comment by paoloczi** [comment]
@bagashe just added the ability to start the assembly with an existing but empty assembly directory (commit 5e51b72d6a4435b830aded183bbba35c733b5c0e). This change will be available in the next release, but in the meantime you can download a test build by clicking on `Artifacts` in [this page](https://github.com/chanzuckerberg/shasta/runs/941771467) and selecting the build artifact you want to download (probably `shasta-Linux`). For more information on downloading a test build, see [here](https://chanzuckerberg.github.io/shasta/BuildingFromSource.html#DownloadTestBuild).

Please let us know if this satisfies your needs.

**Comment by BCArg** [comment]
Thanks very much for adapting this. I have already run my analyses and called Shasta outside of snakemake. Next time I will use shasta I will use the new release and test it.

In the meantime I would suggest to keep this issue opened, so that other users potentially  willing to integrate shasta into snakemake have the instructions available.

**Comment by paoloczi** [comment]
Sure, we will close it when we create a new release . At that point your users will just able to use the standard released version of Shasta.

Keep in mind what I pointed you to is not a new release, but a current test build. It contains all changes in the latest code but it only receives minimal testing and can only be identified by a git commit, not a release number.

**Comment by BCArg** [comment]
OK, thanks for heads up, I will probably wait for the new release.

**Comment by paoloczi** [comment]
Shasta 0.6.0 was released today and implements the requested behavior: the assembly will start even if the assembly directory already exists, as long as it is empty.
