### ISSUE TITLE
Short contigs from Shasta

### ISSUE THREAD

**Issue by Yechao94** [chanzuckerberg/shasta#189]
I use Shasta to assemble the unaligned reads(ONT) I extracted from 500 human samples. The total reads are almost 900G. Then I use all the reads to assemble, the `minReadLength = 15000`  `consensusCaller = Bayesian:guppy-3.0.5-a` .  I got 18571 contigs, but there are many short contigs (such as: >352 length 46  >354 length 88 >356 length 18 .) I wonder why there are such short contigs?
I also polish by MarginPolish-HELEN pipeline. There were only 1108 remaining contigs after polish. I want to know why the results are so different after polish?  In addition, why most of the contigs obtained are shorter than the selected minimum length  `minReadLength = 15000` ?
Here is the result from QUAST:
Before polish:
```
Assembly        Shasta_all_15k
# contigs (>= 0 bp)     18571
# contigs (>= 1000 bp)  7493
# contigs (>= 5000 bp)  1737
# contigs (>= 10000 bp) 597
# contigs (>= 25000 bp) 164
# contigs (>= 50000 bp) 59
Total length (>= 0 bp)  47462375
Total length (>= 1000 bp)       44283040
Total length (>= 5000 bp)       30532617
Total length (>= 10000 bp)      22766683
Total length (>= 25000 bp)      16331745
Total length (>= 50000 bp)      12760669
# contigs       9738
Largest contig  4435345
Total length    45913373
GC (%)  49.22
N50     9842
N75     3666
L50     617
L75     2649
# N's per 100 kbp       0.00
```

After polish:
``` 
Assembly        Shasta_all_15k
# contigs (>= 0 bp)     1108
# contigs (>= 1000 bp)  1046
# contigs (>= 5000 bp)  794
# contigs (>= 10000 bp) 492
# contigs (>= 25000 bp) 159
# contigs (>= 50000 bp) 58
Total length (>= 0 bp)  24110517
Total length (>= 1000 bp)       24064208
Total length (>= 5000 bp)       23298063
Total length (>= 10000 bp)      21073053
Total length (>= 25000 bp)      15951939
Total length (>= 50000 bp)      12497678
# contigs       1106
Largest contig  4337994
Total length    24109899
GC (%)  50.68
N50     54367
N75     16979
L50     50
L75     263
# N's per 100 kbp       0.04
```
Thank you in advance.

**Comment by paoloczi** [comment]
To help us diagnose, please post `AssemblySummary.html` from your assembly directory.

**Comment by Yechao94** [comment]
Thanks for your reply, the file is here:
[AssemblySummary.zip](https://github.com/chanzuckerberg/shasta/files/5181291/AssemblySummary.zip)

**Comment by paoloczi** [comment]
According to Shasta output, there were a total 480 Gb of sequence (not 900 Gb per your initial post), of which about 300 Gb were used in the assembly and the rest were discarded because the reads were shorter than your read length cutoff of 15 Kb. This means that this assembly had coverage 100X. While it is probably possible to tune Shasta for such high coverage, the default parameters you are using are certainly not suited. In fact, even the supplied configuration files (in the `conf` directory) are tuned for coverage around 60X.

So I suggest the following:

* Instead of default parameters, use configuration file `Nanopore-Dec2019.conf`. You can use Shasta option `--config` to specify the configuration file. If an option is specified both in the configuration file and on the command line, the value on the command line takes precedence.
* Increase your read length cutoff from 15 Kb to a value that will result in coverage around 60X to 80X or a total around 200 Gb. You can use file `Binned-ReadLengthHistogram.csv` as guidance to decide a suitable read length cutoff. Future releases of Shasta will provide an option to perform this adjustment of read length cutoff automatically.

If all is good, with your data you should get an assembly with N50 of at least 10 Mb. If you still don't get a satisfactory assembly, please comment here and include the following files form the assembly directory:

* `AssemblySumary.html`
* `LowHashBucketHistogram.csv`
* `MarkerGraphVertexCoverageHistogram.csv`

Regarding polishing: the polisher works by mapping reads to assembled sequence. With an assembly so fragmented, it is no surprise the polisher did not work. However, for the future, for faster/better feedback on polishing issues it is best to file issues to the MarginPolish or HELEN GitHub repositories.

**Comment by Yechao94** [comment]
I followed your suggestion and used the corresponding config file `Nanopore-Dec2019.conf`. And I increase the read length from 15kb to 18k/20k as a test.  The final results are all around ~18M.  
After careful consideration of the results obtained, I realize that there is something wrong with the calculation of this coverage.  The purpose of my experiment is to assemble a non-reference genome sequence. I have 500 samples, but the coverage of each sample is relatively low (~14X), so I merged unmapped reads from all samples. Therefore, the coverage of the sequence I want to assemble is much greater than 100X.  So I also tried to assemble each individual, and then merge the results. 

I tried to use a sample with 24x coverage do a whole genome de novo assembly. According to the discussion of low-coverage assembly #7 ,but the results was only ~2.2G.  In order to achieve 60x coverage, I merged three samples for assembly, and the result was around 2.7G. 
Here is the results file: 
[shasta.zip](https://github.com/chanzuckerberg/shasta/files/5205637/shasta.zip)

**Comment by paoloczi** [comment]
> I followed your suggestion and used the corresponding config file Nanopore-Dec2019.conf. And I increase the read length from 15kb to 18k/20k as a test. The final results are all around ~18M. After careful consideration of the results obtained, I realize that there is something wrong with the calculation of this coverage. The purpose of my experiment is to assemble a non-reference genome sequence. I have 500 samples, but the coverage of each sample is relatively low (~14X), so I merged unmapped reads from all samples. Therefore, the coverage of the sequence I want to assemble is much greater than 100X. So I also tried to assemble each individual, and then merge the results.

I am not sure I understand the process. Is this assembly only using unmapped reads? If so, I am not sure what to expect in terms of assembly results. In this assembly, the majority of the reads (98%) were isolated in the read graph, and a very small number of alignments was found, so no surprise nothing was assembled. You say you understand why this assembly was flawed, but I am not sure I do (unless you really only used unmapped reads), and therefore it is hard for me to guess what is going on here. Perhaps if you clarify your process a bit I may be able to contribute more here.

If you have 500 samples at 14X, total coverage is 700X, so you should be able to get a good assembly representing "average" sequence by using all the reads (not just unmapped reads) and just increasing read length cutoff until coverage reaches 70X or so. 

> I tried to use a sample with 24x coverage do a whole genome de novo assembly. According to the discussion of low-coverage assembly #7 ,but the results was only ~2.2G.

Even though the 2.2 Gb were assembled, the N50 is no longer than a read length, so this did not work. There is work in progress that should enable assemblies at 20X, but I aware that the current implementation does not do too well at low coverage. It may be possible to obtain a reasonable assembly by more tweaking of assembly parameters. But your best bet here is to wait a bit until the current work to assemble at coverage 20X pans out.

> In order to achieve 60x coverage, I merged three samples for assembly, and the result was around 2.7G.

Actually, this assembled about 2.8 Gb (2.797 to be exact) with an N50 of 3.7 Mb, so this is the closest you came so far to a usable assembly. The amount of sequence assembled is about what I would expect under your circumstances, but the N50 is low (but at least measured in Mb, not Kb!). The next thing to do here is look at GFA output to find out if the assembly is "fragmented" (N50 limited by dead ends in the read graph) or "messy" (N50 limited by branches in the read graph). I suggest [Bandage](https://rrwick.github.io/Bandage/) for that. You can also use the [Shasta http server](https://chanzuckerberg.github.io/shasta/InspectingResults.html) to inspect the assembly in more details. And I have to ask the question again here: for this assembly, did you use all reads, or only unmapped reads?

I am also noticing very low CPU utilization in these assemblies. In a healthy machine configuration, Shasta assemblies achieve around 50% CPU utilization. How much memory does your machine have? Where other users also using the same machine while Shasta was running? What choice did you use for options `--memoryMode` and `--memoryBacking`? The most performing choice for large assemblies is `--memoryMode filesystem --memoryBacking 2M` (but it requires root access to the machine).

**Comment by Yechao94** [comment]
> You say you understand why this assembly was flawed, but I am not sure I do (unless you really only used unmapped reads), and therefore it is hard for me to guess what is going on here. 

Yes, the reads here I used in the assembly is the unmapped reads (I got the reads by `samtools view -f 4 xx.bam > unmapped.bam` )

> If you have 500 samples at 14X, total coverage is 700X, so you should be able to get a good assembly representing "average" sequence by using all the reads (not just unmapped reads) and just increasing read length cutoff until coverage reaches 70X or so.

This is a huge job, so the strategy I am adopting now is to first select samples with a high coverage for assembly, such as larger than 20X 

> And I have to ask the question again here: for this assembly, did you use all reads, or only unmapped reads?

For the denovo assembly, I used all reads from one sample.

> I am also noticing very low CPU utilization in these assemblies. The most performing choice for large assemblies is --memoryMode filesystem --memoryBacking 2M (but it requires root access to the machine).

I do not have root access on the cluster.

I am testing some parameter settings and view the assembly results, and then I will share the results with you. 
Thanks again for your quick reply.

**Comment by paoloczi** [comment]
Using only unmapped reads as input to the assembler is not a procedure that I would recommend, and I am not surprised that with that input the assembly was not satisfactory. 

Why do you say assembling all samples together is a huge job? If you increase read length cutoff so that total coverage is around 60X to 80X, the assembly will run in a few hours on a suitable machine - see our paper (link to the paper is in the Shasta README).

**Comment by Yechao94** [comment]
>  If you increase read length cutoff so that total coverage is around 60X to 80X, the assembly will run in a few hours on a suitable machine.

If I only use those long reads for assembly, will it miss those complex region since the reads here could be shorter than others.

> Using only unmapped reads as input to the assembler is not a procedure that I would recommend, and I am not surprised that with that input the assembly was not satisfactory.

Yes, after comparison, the assembly based on unmapped reads don't work. Therefore, I used all the reads of a sample, but merged several samples together (for example, 5 or 8) to meet the coverage requirement. Do you think this result is acceptable?

**Comment by paoloczi** [comment]
> If I only use those long reads for assembly, will it miss those complex region since the reads here could be shorter than others.

Do you expect the reads to be shorter in complex regions? Can you point me to a paper or other source describing this effect?

> Therefore, I used all the reads of a sample, but merged several samples together (for example, 5 or 8) to meet the coverage requirement. Do you think this result is acceptable?

Yes. It will give you an "average" sequence. At each location where there is divergence between the samples, it should pick the alternative sequence with the most coverage.

But for your situation I really suggest using all the samples, and increasing the read length cutoff until coverage is around 60X to 80X. The longer read length cutoff is likely to result in a more contiguous assembly (better N50).

**Comment by paoloczi** [comment]
I am closing this due to lack of discussion. Feel free to reopen it, or create a new issue, if additional discussion topics or questions emerge.
