### ISSUE TITLE
heterozygous plant and k-mer list

### ISSUE THREAD

**Issue by dcopetti** [chanzuckerberg/shasta#190]
Hello,
I would like to test Shasta on a highly heterozygous plant genome I am assembling. The estimated size is ~2.5 Gb, but the high heterozygosity make it look like it is a 5 Gb genome. The goal is then to have a diploid assembly, one fasta for each allele.
I have 226 Gb of PromethION data (called with Guppy 3.0.3, about 45x of 5 Gb genome, N50 15 kb - if I keep e.g reads above 10 kb I still have 31x cov and 25 kb N50), and Flye gave me a 3.7 Gb assembly (N50 700 kb), with about 400 Mb of collapsed haplotypes - likely from homozygous regions that it can't disentangle.
I am trying to see if Shasta can resolve those, as well as trying to get above the 4 Gb of assembly size - thus having most of the allelic regions resolved.

I saw you did a lot of work tweaking parameters for a tomato genome, and I was thinking to try a parameter sweep to see what works best. On which ones would you focus at first? Are there other tweaks I could test?
```
--Align.maxSkip 50
--MinHash.m 3
--MinHash.minBucketSize 3
--MinHash.maxBucketSize 30
--MinHash.minHashIterationCount 30
--MinHash.minFrequency 3
```
How important is the min read length parameter? Should I try to stay above/around 40x per allele, even at cost of including many reads <10 kb (that could be just contained into others)?

Lastly, I figured out a way to isolate only highly informative k-mers, and I am thinking to supply them as a list. Which format should that file be? just a sequence in each line?
I see that you moved from 10 to 14 nt k-mers for the newer basecalled data - good. I have on average about 37 of my specific 21-mers per kb, would you still recommend to go down in size to ~14, or can I stay on larger k-mer sizes? I guess it is OK to have k-mer length of an even number.
thanks,

Dario

PS: I see you have a UL version of the conf files and from a quick look it looks like the only difference is min read length. Are those configurations for ultralong reads?
I will have other lines with a read N50 of 37 and >50 kb (guppy 4.0.1), would you switch to UL settings for those?

**Comment by dcopetti** [comment]
After reading the computational methods page, I see that you use compressed k-mers as markers.
Do you think it will be an issue if my list of k-mers/markers is not compressed?
Or better, do you know of a way to compress Illumina reads prior to k-mer counting?

I think I have a way to get you the "most efficient" set of markers (no repeats, single copy) to get the graph with less branches. The whole Shasta algorithm does not need to be touched, but I think we can improve the specificity of each edge.
I'd love to discuss these steps with you, thanks

**Comment by paoloczi** [comment]
One more thought: you can use the Shasta http server functionality to explore your assembly results. In particular, looking at the read graph will help you assess the amount of haplotype separation achieved. See [here](https://chanzuckerberg.github.io/shasta/InspectingResults.html) for details. Given that you have a small assembly, I suggest running your assembly with `--memoryMode filesystem --memoryBacking disk`.

**Comment by paoloczi** [comment]
I am closing this due to lack of discussion. Feel free to reopen it, or create a new issue, if additional discussion topics or questions emerge.
