### ISSUE TITLE
Running  E.coli genome denovo assembly

### ISSUE THREAD

**Issue by ytalhatamer** [chanzuckerberg/shasta#197]
Hi I am running an E.coli genome denovo assembly of a clinical strain. We have ONT Minion sequence with N50: 15kb. 

I am running shasta in Macbook pro 15' (2015) with 16GB ram and enough storage.  I get the following error is there anyway to understand  is the problem with the fastq file  or with one read?

2020-Oct-01 12:29:20.964805 Begin loading reads from 1 files.
2020-Oct-01 12:29:20.964846 Loading reads from /Users/ytalhatamerlab/OneDrive - University of Texas Southwestern/ONT_deNovo_Assembly/SP3_both.fastq
2020-Oct-01 12:29:35.733465 Terminated after catching a runtime error exception:
Error reading from /Users/ytalhatamerlab/OneDrive - University of Texas Southwestern/ONT_deNovo_Assembly/SP3_both.fastq near offset 0

**Comment by paoloczi** [comment]
It is possible that there are problems related to white space in the file name. Perhaps the white space needs to be escaped when invoking Shasta? To check for this, you could try moving the file to a path without without space (for example `/tmp` if your system has it), or creating a symbolic link to it at a location without white space in its path.

**Comment by paoloczi** [comment]
Another thing to try: enclose the entire path to the fastq file in quotes when invoking Shasta.

**Comment by paoloczi** [comment]
Also: we don't have a configuration file tuned for MinION reads. Using default parameters you will not necessarily get a satisfactory assembly, so some tuning of assembly parameters may be necessary. I would start with `--Reads.minReadLength 5000 --Assembly.consensusCaller Modal`. Depending on coverage, thay might not be sufficient to give you a satisfactory assembly. If you post `AssemblySummary.html` for your assembly we can help with selection of assembly parameters.

**Comment by paoloczi** [comment]
I am closing this due to lack of discussion. Feel free to reopen it or create a new issue if needed.
