### ISSUE TITLE
Runtime error exception: AssemblyPathGraph2.cpp line 635 - With minReadLength = 6000

### ISSUE THREAD

**Issue by EinarBaldvin** [chanzuckerberg/shasta#213]
[shasta_run.log](https://github.com/chanzuckerberg/shasta/files/5567750/shasta_run.log)

I am encountering an odd problem during detangling. When assembling with reads.minReadLength = 6000, shasta-0.6.0 encounters a runtime error "AssemblyPathGraph2.cpp line 635". However, it completes the assembly with read lengths 3000,5000, and 7000.

**Comment by paoloczi** [comment]
Thank you for reporting this. Would it be possible for you to share the input data and the command line you used, so we can reproduce and debug the problem? If you prefer we can arrange to do this privately.

As a temporary workaround, you could switch to detangle method 1 (via `--Assembly.detangleMethod 1`) or turn detangling off completely (via `--Assembly.detangleMethod 0`). However both of these solutions would reduce assembly contiguity.

Separately, I generally don't recommend using Shasta with such short read lengths for nanopore reads. We usually use a read length cutoff of 10 Kb or more. Nanopore reads are long enough that the coverage loss incurred is generally acceptable, and the shorter reads have a tendency to create assembly problems.

**Comment by EinarBaldvin** [comment]
I still have fairly low coverage of my data ~30x, and quite short reads, and was experimenting with different read lengths as shasta is extremely fast.

Here is the command and the config file:
shasta-Linux-0.6.0 --input reads.fasta --threads 54 --config Nanopore-Sep2020_mod_plant.conf --assemblyDirectory $name
[Nanopore-Sep2020_mod_plant.conf.txt](https://github.com/chanzuckerberg/shasta/files/5581551/Nanopore-Sep2020_mod_plant.conf.txt)

About sharing the data, please contact me privately and I need to see if I am allowed to do so.

**Comment by paoloczi** [comment]
Thank you for sharing your configuration file. I tried reproducing the failure using this configuration file with other reads that I have access to, but without success. I could not find an e-mail address to contact you privately regarding sharing the data. Please e-mail me at my e-mail address in the _Shafin et al._ paper cited in the Shasta README file.

A couple of comments on your configuration file - both unrelated to the failure you observed.

-  You use `--MinHash.version 1`. As documented, this option is experimental. It currently offers no advantages relative to `--MinHash.version 0`, and is more expensive computationally.
- I recommend increasing the read length cutoff `--Reads.minReadLength` to at least 10 Kb. With long reads this usually results in a small loss of coverage and better assembly results.
- The choice `MinHash.minFrequency 3` probably results in many low quality alignment candidates, which can reduce assembly performance.

**Comment by paoloczi** [comment]
I was able to reproduce and fix the problem using the reads kindly provided by @EinarBaldvin . The fix is in the latest code on GitHub and will be available in release 0.7.0. To download a current test build containing the fix, follow the directions [here](https://chanzuckerberg.github.io/shasta/BuildingFromSource.html#DownloadTestBuild).

**Comment by paoloczi** [comment]
The fix is in Shasta release 0.7.0.
