### ISSUE TITLE
If MinKNOW was used for basecalling what kind of consensus caller for repeat counts (-- Assembly.consensusCaller) can I use?

### ISSUE THREAD

**Issue by ElviraTo** [chanzuckerberg/shasta#233]

**Comment by paoloczi** [comment]
Since we don't have a Bayesian model for that base caller, you can use `--Assembly.consensusCaller Modal`. That chooses the most frequent repeat count at each assembled position. See [here](https://chanzuckerberg.github.io/shasta/ComputationalMethods.html#RepeatCounts) for more information.

**Comment by ElviraTo** [comment]
@paoloczi Thank you!
