### ISSUE TITLE
errors for 1g genome assembly

### ISSUE THREAD

**Issue by bitcometz** [chanzuckerberg/shasta#24]
hi, I used the following commands:
**shasta-Linux-0.1.0 --input /filt_adapter.fasta --Reads.minReadLength 20000**

and got the error informations:

Processing 2147475201 input characters.
Block processed in 2.08425 s.
Reads for this block stored in 2.01474 s.
2019-May-24 15:05:39.949279 Reading block 109521666048 111669149696, 2147483648 bytes.
Block read in 8.90425 s at 2.41175e+08 bytes/s.
Processing 2147472802 input characters.
Block processed in 2.35328 s.
2019-May-24 15:06:19.564782 Terminated after catching a runtime error exception:
Error 14 during mremap call for MemoryMapped::Vector: Bad address

Best,

**Comment by paoloczi** [comment]
What platform are you on? How much memory and swap space do you have? It could be a memory issue. The error messages are a bit rough in this initial release.

**Comment by paoloczi** [comment]
One more comment: for a large assembly like this one you can get better performance by using huge pages - see the documentation sections "Maximizing assembly performance" and "Memory modes" under "Running an assembly". However some of these options require root privilege. 

If you are assembling a 1 Gb genome, you will probably need a machine with 700 GB of memory for the assembly to complete. On a machine with 32 cores (64 virtual CPUs) your assembly should run in 2 to 4 hours, assuming you are at coverage around 60x.

**Comment by bitcometz** [comment]
Thanks!
I run it on the platform Linux with memory configuration of 80G at most.
Yes, it should be a memory issue.
However, I think such a large memory requirement is beyond the capacity of many labs.

Best

**Comment by colindaven** [comment]
Running a 3 GB ONT human assembly as a test,  I guess I have a similar issue. I only have 512GB RAM on my nodes, so I guess I need 2 TB or so for this to complete judging by the above comments. I guess I'll have to rent a big cloud node if I can to get this done.

I'm sure the assembler will be great for our many smaller projects though, so thanks for providing an alternative to canu et al.

```
Found a strand jump region with 254 vertices near read 116372.
This strand jump region contains 928 edges.
Found 1178 strand jump regions.
Marked 18344 read graph edges out of 52501956 total as cross-strand.
2019-May-27 15:01:28.550094 End flagCrossStrandReadGraphEdges.
2019-May-27 15:01:28.633676 Begin flagging chimeric reads, max distance 2
Using 56 threads.
2019-May-27 15:01:28.633761 Processing 9914367 reads.
2019-May-27 15:01:37.473575 Done flagging chimeric reads.
2019-May-27 15:01:37.502717 Flagged 303540 reads as chimeric out of 9914367 total.
Chimera rate is 0.0306162
2019-May-27 15:01:37.573958 Computing connected components of the read graph.
The read graph has 7112909 connected components.
2019-May-27 15:01:47.071843 Done computing connected components of the read graph.
Processing self-complementary component 0 with 6718164 oriented reads.
Processing self-complementary component 1 with 102030 oriented reads.
Processing self-complementary component 4 with 92106 oriented reads.
Processing self-complementary component 5 with 86250 oriented reads.
Processing self-complementary component 6 with 64580 oriented reads.
Processing self-complementary component 15 with 38914 oriented reads.
Processing self-complementary component 22 with 31910 oriented reads.
Processing self-complementary component 31 with 21326 oriented reads.
Processing self-complementary component 42 with 16968 oriented reads.
Processing self-complementary component 91 with 12174 oriented reads.
Processing self-complementary component 92 with 12164 oriented reads.
Processing self-complementary component 209 with 6542 oriented reads.
Processing self-complementary component 218 with 6278 oriented reads.
Processing self-complementary component 253 with 5656 oriented reads.
Processing self-complementary component 518 with 2642 oriented reads.
Processing self-complementary component 525 with 2592 oriented reads.
Processing self-complementary component 596 with 2124 oriented reads.
Processing self-complementary component 767 with 1380 oriented reads.
Processing self-complementary component 962 with 922 oriented reads.
2019-May-27 15:01:53.787047 Begin computing marker graph vertices.
Using 56 threads.
2019-May-27 15:02:17.033051 Terminated after catching a runtime error exception:
Error 12 during mremap call for MemoryMapped::Vector: Cannot allocate memory
```

**Comment by paoloczi** [comment]
In the last few years machines with large amounts of memory at reasonable prices have started to appear. However, it is true that they are not yet widely available.

I have the same problem the two of you, and probably others, have bumped into, as my organization (Chan-Zuckerberg Initiative) does not have any computing facilities except for employee laptops. Fortunately, however, large memory machines are available to rent by the hour at very reasonable prices on the major cloud computing platforms. We use AWS, and for human genomes I have been using instance type x1.32xlarge, with 1952 GB of memory and 128 virtual processors, at a cost of $13/hour approximately. On this machine, a typical human assembly takes 5-6 hours at a compute cost below $80, much lower than the sequencing costs required to produce the reads. Prices 2 to 3 times lower are also available for reserved instances and on the spot market.

For the 1 Gb genome that bitcometz tried to assemble, I estimate that a machine with around 700 GB of memory will be sufficient. For this, an AWS r5.24xlarge instance, with 768 GB of memory and 96 virtual processors, should do the job. It is available on demand for around $6/hour. The assembly should complete in 2 hours or so, at a cost  less than $20, again small compared to sequencing costs. And here too, you could also get prices 2x or 3x lower by using reserved instances or using the spot market. 

My guess is that, if you figure out the current cost of an assembly using available alternatives and smaller machines, including the amortization cost of the machines, you will end up with a significantly higher cost than $20 per assembly for a 1 Gb genome.

**Comment by bitcometz** [comment]
Dear paoloczi,

You are right !!!
But, uploading the data will also takes a lot of time .
In assembly community, most people has a machine less than 512G or 128G.
Falcon and Canu is very time consuming and required memory less than 128G. 
As far as I am concerned,  I can accept a few days to get the assembly results.
Is there a way to make memory much lower, even at the expense of speed?
Thanks for you amazing tool and help !!!

Best

**Comment by paoloczi** [comment]
Uploading the input reads is generally not too much of a problem. Say you want to do a 60x assembly for your 1Gb genome. The size of your fasta file will be about 60 GB. If you compress it it will go down to 20 GB. On a 80 Mb/s internet connection (10 MB/s) that will upload in about half an hour. If you use AWS, I suggest uploading to S3 storage. Once the upload is complete and you star your instance, copying the data from S3 to local instance storage is fast (100 MB/s or better)  and will take just a few minutes.

For compressing/decompressing, I suggest using pbzip2. It is much faster than alternatives as it uses all available compute power.

So, I still think your best option is to spend a few dollars running your assembly on an instance on the cloud, particularly if you keep in mind that the sequencing cost to produce the reads was much higher than that.

However, if you still insist on running locally on a small machine, you could try the following Shasta options:
```
--memoryMode filesystem --memoryBacking disk
```
See [here](https://chanzuckerberg.github.io/shasta/Running.html#MemoryModes) for more information. However, don't tell anybody that I suggested this as I don't really recommend it: it will cause all Shasta data structures to be allocated in memory mapped files stored on disk, which will slow things down, perhaps intolerably, depending on how much memory the run requires, how much memory your machine has, and whether your storage is disk or SSD. Also, for this to work you will need to have sufficient space available on disk (around 700 GB or so for your 1 Gb genome assembly).

**Comment by paoloczi** [comment]
I added a [documentation section](https://chanzuckerberg.github.io/shasta/Running.html#MemoryRequirements) summarizing this conversation.
