### ISSUE TITLE
What config should be used for reads basecalled with a mix of guppy versions?

### ISSUE THREAD

**Issue by gitcruz** [chanzuckerberg/shasta#243]
Hi Paolo,

Reading the output logs and the docs, I noticed  that is necessary to use a config file in concordance with the basecaller version. For a project with standard reads, i do have Guppy4.2.3 so I am just rerunning the assembly with Nanopore-Sep2020.conf. This is what you recommend for  Guppy3.6.0 or greater.

However, for another project I do have a mix of flowcells sequenced at different times:

- 2 out of 12 flowcells  basecalled with guppy3.2.6. 
- 3 out 12 basecalled with guppy3.2.10.
- 8 out 12 basecalled with guppy4.0.11.

What would you recommend in such case? Is it reasonable to try assembling the genome with --config Nanopore-Sep2020.conf ? 

I know the best thing to do should be re-basecalling all of them with 4.0.11...but this is a bit complicated without modern GPU nodes and it will slow down things.
 
Thanks,
Fernando

**Comment by paoloczi** [comment]
My recommendation would be to use `Nanopore-Dec2019.conf` for the flowcells basecalled with Guppy 3.2.6 and 3.2.10, and `Nanopore-Sep2020.conf` for the flowcells basecalled with Guppy 4.0.11.

There was a huge improvement in Guppy at version 3.6, so your data quality would improve substantially if you were able to redo the base calling for those 5 older flowcells. But I do understand the complexities of that.

**Comment by gitcruz** [comment]
Hi Paolo,
So is it possible to specify a different configuration file for each read
file?  What would be the syntax?

Do you think something like this would work?

shasta  -input reads/FC1_guppy3.2.6.fasta reads/FC2_guppy3.2.10.fasta
reads/FC3_guppy4.0.11.fasta ---assemblyDirectory out --config
/absolute-path-to/Nanopore-Dec2019.conf
/absolute-path-to/Nanopore-Dec2019.conf
/absolute-path-to/Nanopore-Sep2020.conf

I definitely think we should rebasecall.

Thanks,
F

**Comment by paoloczi** [comment]
Sorry, I misread your question. No, you can't do that. You will have to pick one. Given that, I suggest using `Nanopore-Dec2019.conf` until you can redo the base calling.

**Comment by gitcruz** [comment]
Sure, that makes more sense.
Thanks,
Fernando

**Comment by paoloczi** [comment]
I am closing this due to lack of discussion, but feel free to reopen it or create a new issue if additional discussion topics emerge.
