### ISSUE TITLE
MacOS build fails due to failure to install SeqAn

### ISSUE THREAD

**Issue by paoloczi** [chanzuckerberg/shasta#247]
MacOS builds on GitHub Actions are failing due to a problem installing the SeqAn2 library.

The following command in `shasta/scripts/InstallPrerequisites-macOS.sh` is used to install the SeqAn2 library:
```
brew install brewsci/bio/seqan@2
```
That command currently fails with the following messages:

```
==> Installing seqan@2 from brewsci/bio
==> Downloading https://archive.org/download/brewsci/bottles-bio/seqan%402-2.4.0.catalina.bottle.tar.gz
curl: (22) The requested URL returned error: 403 
Error: Failed to download resource "seqan@2"
Download failed: https://archive.org/download/brewsci/bottles-bio/seqan%402-2.4.0.catalina.bottle.tar.gz
```

Manual download of that file via `wget` also fails similarly:

```
wget https://archive.org/download/brewsci/bottles-bio/seqan%402-2.4.0.catalina.bottle.tar.gz
--2021-04-07 09:57:49--  https://archive.org/download/brewsci/bottles-bio/seqan%402-2.4.0.catalina.bottle.tar.gz
Resolving archive.org (archive.org)... 207.241.224.2
Connecting to archive.org (archive.org)|207.241.224.2|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2021-04-07 09:57:50 ERROR 403: Forbidden.
```

It could be that this is an intermittent failure of the `brewsci` server. However, it is possible that this is not the correct way to install SeqAn2 on macOS. In this case, we need to fix the installation command.

I will have to disable macOS builds on GitHub Actions until this is fixed. If we don't have a fix by the time we create the next release, we will have to exclude macOS from the release.

**Comment by paoloczi** [comment]
Today (4/13/2021) I noticed that the above `wget` no longer fails. Therefore I tried re-enabling the macOS 10.15 build. However installation of SeqAn2 still fails. The error is different now:

```
==> Installing seqan@2 from brewsci/bio
==> Downloading https://ghcr.io/v2/brewsci/bio/seqan%402-2.4.0.catalina.bottle.tar.gz
curl: (22) The requested URL returned error: 404 
Error: Failed to download resource "seqan@2"
Download failed: https://ghcr.io/v2/brewsci/bio/seqan%402-2.4.0.catalina.bottle.tar.gz
```

A manual `wget` gets the same error.

**Comment by ASLeonard** [comment]
I run shasta on a linux cluster, but I have a macOS laptop, so I had been keeping up with this out of curiosity. My mac is version `10.15.7 (19H524)`

Previously both the brew and wget attempts failed with the same errors you had, but as of just now the brew approach works.
```
brew install brewsci/bio/seqan@2

==> Installing seqan@2 from brewsci/bio
==> Downloading https://ghcr.io/v2/brewsci/bio/seqan/2/manifests/2.4.0
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/brewsci/bio/seqan/2/blobs/sha256:1fe83b7b478611b6fc28fe4eb7bc34e8d7846c6bc8dda57ae37d3e4e40d9e821
==> Downloading from https://pkg-containers-az.githubusercontent.com/ghcr1/blobs/sha256:1fe83b7b478611b6fc28fe4eb7bc34e8d7846c6bc8dda57ae37d3e4e40d9e821?se=2021-04-14T13%3A00%3A00Z&sig=eugiAhp1baiwqKcp3zS%2FWPETp3FLgz9aAAo0%2FLVB%2Bb4%3D&sp=r&spr=https&sr=b&sv=2019-12-12
######################################################################## 100.0%
==> Pouring seqan@2--2.4.0.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/seqan@2/2.4.0: 1,888 files, 35.1MB
```

The wget download also works fine now.

**Comment by paoloczi** [comment]
Thank you for the tip @ASLeonard! Based on this, I will try and re-enable to macOS 10.15 build one more time.

**Comment by paoloczi** [comment]
Yes, the macOS 10.15 build is back to life. I will leave this issue open for a bit in case the problem shows up again, as it has been intermittent.

Thank you for your help @ASLeonard!

**Comment by paoloczi** [comment]
The macOS build is failing again with the same error. I will leave it on for now so we can see if it comes back to life.

**Comment by ASLeonard** [comment]
It seems to be working again (hopefully for more than a day this time).

**Comment by paoloczi** [comment]
Yes. The last failure was 8 days ago. If it makes it two weeks I will close this issue, and I can always reopen it if the problem reappears.

**Comment by paoloczi** [comment]
These intermittent server failures have disappeared, at least for now, so I will close this issue.
