### ISSUE TITLE
Support newer versions of boost?

### ISSUE THREAD

**Issue by dpryan79** [chanzuckerberg/shasta#25]
[This header file](https://github.com/chanzuckerberg/shasta/blob/master/src/AlignmentGraph.cpp#L21) was removed in boost 1.68, which is the version currently used in conda. Would it be possible to support boost >=1.68?

**Comment by paoloczi** [comment]
I will look into that, it should not be a problem. But the Shasta executable is linked statically and does not rely on the presence of Boost libraries. So, unless for some reason you want to build the code yourself, you can just use the released executable regardless of what Boost version is installed on your machine.

Can I ask what Linux platform you are using? The current code is only known to build on Ubuntu 16.04 and Ubuntu 18.04, with boost installed via `apt` (this is done by `shasta-install/bin/InstallPrequisites-Ubuntu.sh`). Perhaps conda installs a different version from what `apt` does. In any event, I can certainly look into supporting newer versions of Boost.

**Comment by dpryan79** [comment]
Our docker containers are centos 6 based, if memory serves. I noticed that the binary is statically linked, so that should suffice for the moment. Does shasta need binaries from `spoa` or `marginPhase` during run time?

**Comment by paoloczi** [comment]
The statically linked binary should run on centos 6, but please let me know if this is not the case. You don't need anything else - spoa is linked statically and marginPhase is not supported by the static executable (and in any event the marginPhase functionality is not ready for prime time).

**Comment by dpryan79** [comment]
Great, that makes life easy then.
