### ISSUE TITLE
question on the Markers section of documentation

### ISSUE THREAD

**Issue by rchikhi** [chanzuckerberg/shasta#26]
Dear Shasta authors,

I was glad to see your London Calling presentation on twitter and the performance of the assembler looks impressive. I just had a small question concerning the section "Markers" at page https://chanzuckerberg.github.io/shasta/ComputationalMethods.html

In the first marker example given, CGC appears 3 times in the read (CGACACGTATGCGCACGCTGCGCTCTGCAGC) yet it is used only once as a marker, is this intentional or a mistake? This is also the case for TGC.

Best,

Rayan

**Comment by paoloczi** [comment]
Thank you for your careful reading of the documentation! I created that example by hand, and you found multiple errors in it. They are fixed now - at least I hope! Thanks again.
