### ISSUE TITLE
ERROR: guppy-5.0.7-a is not a built-in Bayesian model

### ISSUE THREAD

**Issue by madagiurgiu25** [chanzuckerberg/shasta#264]
Hi, 

According to the documentation https://chanzuckerberg.github.io/shasta/ComputationalMethods.html#IterativeAssembly
the guppy-5.0.7-a should be available as Bayesian model. I installed `shasta-Linux-0.7.0` from source but when I tried running the assembly with this preset I received the following error:

Command:
`./shasta-Linux-0.7.0 --input $input  --Assembly.consensusCaller Bayesian:guppy-5.0.7-a `

Error:
`guppy-5.0.7-a is not a built-in Bayesian model and could not be open as a configuration file. Valid built-in choices are: guppy-2.3.1-a, guppy-2.3.5-a, guppy-3.0.5-a, guppy-3.4.4-a, guppy-3.6.0-a, r10-guppy-3.4.8-a`

Do I need to install maybe a different version of Shasta? Thank you!

**Comment by paoloczi** [comment]
As you suspect, this is a feature that was recently added, and it is not in release 0.7.0. The documentation on GitHub Pages  always refers to the latest code on GitHub, and the 0.7.0 documentation (available in the 0.7.0 tar file) does not mention this new option. Sorry about the confusion and inconvenience. 

I hope to have soon a new release that includes this, but in the meantime you can download a current Shasta test build as described [here](https://chanzuckerberg.github.io/shasta/BuildingFromSource.html#DownloadTestBuild). For convenience, the link to download a test build from about a week ago is [here](https://github.com/chanzuckerberg/shasta/suites/3201632937/artifacts/74008103). You must be logged in to GitHub while using this link. After download you have to `unzip` and `chmod` to make it executable, after which you should be able to run it and it should recognize the Bayesian model for Guppy 5.0.7 (which incidentally in my experience creates reads of significantly better quality than was available previously). Let me know if you have any problems doing this.

**Comment by paoloczi** [comment]
Given that you did not comment I assume that you were able to download a test build that includes the new Bayesian model. Therefore I will close this issue, but feel free to reopen it or create a new one if you have additional question or problems.
