### ISSUE TITLE
HG004 Truth Assembly Availability

### ISSUE THREAD

**Issue by janetxinli** [chanzuckerberg/shasta#265]
Hello,

I am analyzing several HG004 assemblies and am interested in using the truth assembly as the reference as was done in your paper. The paper states that the assembly should be available in your Google Cloud Bucket (https://console.cloud.google.com/storage/browser/kishwar-helen/truth_assemblies), however I only see data for the other assemblies mentioned in the paper (E. coli, HG00733, etc). Is the HG004 truth assembly still publicly available? If so, where may I find it?

Thank you!

**Comment by kishwarshafin** [comment]
Hi @janetxinli ,

We did not report the QV value of HG004 as we don't have a high-quality genome assembly available for that sample. We only reported HG002, HG00733 and CHM13: 
<img width="334" alt="Screen Shot 2021-08-11 at 3 57 24 PM" src="https://user-images.githubusercontent.com/10559039/129114193-32a21293-0814-4c12-a677-f65361c46ba7.png">

Do you want to assess your assembly? Over the last years, there have been several developments in terms of evaluating the assembly. As it does not pertain to this issue, I will not expand. Please feel free to send me an email at shafin@ucsc.edu and I can provide you instructions on how to assess the assembly.

**Comment by paoloczi** [comment]
I am closing this due lo lack of discussion. Feel free to reopen it or create a new issue if additional questions arise.
