### ISSUE TITLE
How to specify the output dir ?

### ISSUE THREAD

**Issue by xiucz** [chanzuckerberg/shasta#269]
Hi, 
Aftering reading the document, I still can't get which parameter should I use to specify the output directory. 

How to specify the output dir ?

Best,
xiucz

**Comment by paoloczi** [comment]
The option to do that is `--assemblyDirectory` (default is `ShastaRun`). That option is described [here](https://chanzuckerberg.github.io/shasta/CommandLineOptions.html#assemblyDirectory) and [here](https://chanzuckerberg.github.io/shasta/Running.html#OutputFiles).

To prevent removing existing data, when the assembly starts the specified assembly directory must not exist, or can exist and be empty.

Let us know if additional clarification is needed.

**Comment by xiucz** [comment]
I am sorry to miss so detailed CommandLineOptions page, my mistake. I will close this issue.

Thank you.
xiucz

**Comment by paoloczi** [comment]
No problem. The documentation is not well organized, which can make it hard to locate the piece of information you need. To alleviate this in the future, keep in mind Shasta documentation is indexed by Google, so you can try a Google search to locate the information you want. For example, for this case searching Google for "shasta output directory" gets to the right place:

![image](https://user-images.githubusercontent.com/25391437/142884935-c16f9047-d480-4231-bdb9-bf64970da9cf.png)

You can also use `shasta --help` to get a list of command line options, each listed with a quick description.

In any event, always free to open a new issue if new questions arise or if you are not able to obtain a satisfactory assembly.

**Comment by xiucz** [comment]
Thank you.
