### ISSUE TITLE
Yes, in its current status Shasta is not able to assemble telomere sequence. I am hoping to be able to devote some time later this year to developing algorithm improvements that permit assembly of centromeres and telomeres.

### ISSUE THREAD

**Issue by jflucier** [chanzuckerberg/shasta#271]
Yes, in its current status Shasta is not able to assemble telomere sequence. I am hoping to be able to devote some time later this year to developing algorithm improvements that permit assembly of centromeres and telomeres.

_Originally posted by @paoloczi in https://github.com/chanzuckerberg/shasta/issues/124#issuecomment-620259957_

**Comment by jflucier** [comment]
I am wandering if the assembly of telomeric rsequence is still a concern with Shasta?

Do you have propositions on parameters I can provided that would help telomeric assembly with Shasta?

tks in advance for your help

**Comment by paoloczi** [comment]
A few months ago I was able to assemble telomeric sequence in a separate assembly with custom parameters, after separating out the reads that contained the expected telomeric sequence. This is not as good as assembling telomeric sequence in a standard assembly, but could be useful in some situations. I can dig out the details of those experiments, but that will take me a couple of days. I will post that information here soon.

**Comment by paoloczi** [comment]
I reviewed my notes and here is the procedure I used a few months ago to successfully assemble telomeric sequence:

* Find and separate the reads containing telomeric sequence. These reads will also contain some adjacent sequence, of course, but you don't have to search for that. This step was done outside Shasta.
* Run Shasta using the appropriate standard configuration, but using as input only the reads separated out in the previous step. For example, if you are using Shasta 0.8.0 and you have Guppy 5 reads, you can use `shasta --config Nanopore-Oct2021 --input ReadsFromPreviousStep.fasta`.

It is also possible that your standard assembly done with all the reads and the appropriate configuration may contain some telomeric sequence, but we have never studied that in detail.

**Comment by jflucier** [comment]
Thank you for your quick response. I will try it out.

tks

**Comment by paoloczi** [comment]
I am closing this due to lack of discussion, but feel free to reopen it or create a new issue if additional questions or discussion topics emerge.
