### ISSUE TITLE
Allow multi-line reads in input fasta files

### ISSUE THREAD

**Issue by paoloczi** [chanzuckerberg/shasta#28]
Currently Shasta requires each read in an input Fasta file to be on a single line. It would be good to remove this restriction, as the fasta format does allow reads to span multiple lines, and some utilities do create fasta files with reads over multiple lines.

**Comment by aclum** [comment]
Can this be reopened? I'd consider this a bug as fasta specification allows for multiple lines per line.

**Comment by paoloczi** [comment]
I closed issue #29 because the exception was due to the unsupported multi-line reads. However issue #28, this issue, is still open, and I consider it a valid request for the reasons that you state. Therefore, I hope that this request will be addressed at some point. However I cannot promise when this might happen, as I am giving priority to developing more advanced assembly algorithms or other functionality for which no workaround is available. 

The workaround for this is to preprocess the fasta file using a script to remove the line ends embedded in the reads. It is a hassle and requires an additional pass to disk, but can be easily implemented separately from the assembler. If you happen to write such a script I would encourage you to submit it in a pull request to be added in the shasta/scripts directory, so it would become available to other interested users.

**Comment by paoloczi** [comment]
From a quick look on the web there are various places where people have proposed easy ways to do that conversion.

**Comment by paoloczi** [comment]
This was fixed and the latest code supports multi-line reads in fasta files. It also supports Windows line ends and reads with invalid or no-called bases, which are discarded.

**Comment by robertriley6** [comment]
Can we re-open this issue?

On Oct 11 I pulled the docker container and found the issue to still be there:

docker pull tpesout/shasta

docker run -v /home/ec2-user:/home/ec2-user tpesout/shasta --input /home/ec2-user/junk/test.fasta --assemblyDirectory test0

Shasta development build. This is not a released version.
2019-Oct-12 00:15:30.361512 
...
2019-Oct-12 00:15:30.519118 A runtime error occurred in thread 0: The sequence of each read must be on a single line of the input fasta file.


Thanks.

**Comment by paoloczi** [comment]
As I said in my comment above, this is fixed in the latest code on GitHub. You have three choices to get this change:

- Download a current test build (directions [here](https://chanzuckerberg.github.io/shasta/BuildingFromSource.html#DownloadTestBuild)).
- Build it yourself (directions [here](https://chanzuckerberg.github.io/shasta/BuildingFromSource.html)).
- Wait for the next release.
