### ISSUE TITLE
Error in assembly: exception occurred in processing input characters

### ISSUE THREAD

**Issue by ramyavijayram** [chanzuckerberg/shasta#29]
Hi! I have been trying Shasta for the assembly of both simulated and experimental nanopore reads. While reading the input files, in some cases, I have been getting the following error:

A standard exception occurred in thread 3: Assertion failed: buffer[bufferIndex++] == '>' at void ChanZuckerberg::shasta::ReadLoader::processThreadFunction(std::size_t) in /home/paolo/shasta/src/ReadLoader.cpp line 274

What does this error mean? 

I have been running shasta with the default parameters, with the following command:
**./shasta-Linux-0.1.0 --input inputfile.fasta**

The complete log obtained in the terminal is as shown below:

Shasta Release 0.1.0
2019-Jun-03 15:27:41.808391 Loading reads from /g/steinmetz/vijayram/output/dazz_db/JS734_only_circ.fasta.
Input file block size: 2147483648 bytes.
Using 1 threads for reading and 80 threads for processing.
Input file size is 1016091 bytes.
2019-Jun-03 15:27:42.964100 Reading block 0 1016091, 1016091 bytes.
Block read in 0.00115359 s at 8.80809e+08 bytes/s.
Processing 1016091 input characters.
A standard exception occurred in thread 3: Assertion failed: buffer[bufferIndex++] == '>' at void ChanZuckerberg::shasta::ReadLoader::processThreadFunction(std::size_t) in /home/paolo/shasta/src/ReadLoader.cpp line 274
Aborted

Thank you!

**Comment by paoloczi** [comment]
Shasta has a documented limitation that the input fasta files must have each read on a single line of the fasta file - see the section entitled _Input Files_ in [this page](https://chanzuckerberg.github.io/shasta/Running.html) and [this open Shasta issue](https://github.com/chanzuckerberg/shasta/issues/28).

It is likely that this is the reason for the error message you are encountering (sorry the error messages are so bad in this initial release!).

Please verify that in your fasta file each read is on a single line and modify it as necessary. If after checking/verifying you still encounter the problem please attach your input file to the GitHub issue (it is a small file and you can directly drag and drop it to the comment window on GitHub).

It is also possible that your fasta file has some other kind of format error - for example some header material at the beginning, before the first read. Is the first character in the file a ">"?

**Comment by ramyavijayram** [comment]
Making the fasta file single line worked! Thank you!
