### ISSUE TITLE
URL for human ONT data 

### ISSUE THREAD

**Issue by bitcometz** [chanzuckerberg/shasta#41]
Hello, 
I wonder where I can download the eleven human ONT data mentioned in your bioRxiv paper?
Could you provide related URL ?
Thanks !

Best

**Comment by paoloczi** [comment]
Because of an oversight, this is missing from the paper. It will certainly be added for the published version. Here are the links:

https://github.com/human-pangenomics/hpgp-data
https://s3-us-west-2.amazonaws.com/human-pangenomics/index.html

**Comment by paoloczi** [comment]
I added the second of the above links to the top level README.md, so it should be very visible.
