### ISSUE TITLE
limiting core usage

### ISSUE THREAD

**Issue by chklopp** [chanzuckerberg/shasta#42]
Hi,

I did not find a parameter to set the number of cores. Is there one?
shasta seems to try to use all the available cores :
Using 1 threads for reading and 240 threads for processing.

**Comment by paoloczi** [comment]
Shasta is designed to use a dedicated machine, and for that reason that option is not currently provided in the static executable. But I can see that it would be a useful capability to have in some cases. I will leave this issue open and implement this soon.

**Comment by chklopp** [comment]
This will really be helpful because large servers are often shared between users.

**Comment by paoloczi** [comment]
If you have enough memory, that works. For a human assembly, that means a lot of memory. For example, if you had two copies of Shasta doing human assemblies at 60x, you would probably need at least 3 TB. Servers with up to 12 TB have started to appear, so there are certainly situations where sharing would be appropriate and desirable.

**Comment by paoloczi** [comment]
Added option `--threads` in commit 38ce67fc64a4912ffd9b910bae1608a6541db902.

**Comment by chklopp** [comment]
Thank you. 
Could you compile this new version for us?

**Comment by paoloczi** [comment]
Here is a link to a Shasta executable after that commit:

https://drive.google.com/file/d/1moCz2WuV3tKfO--HPpWCpMJFbIIr1bsZ/view?usp=sharing

This is **temporary** and will disappear in a week or so.

Keep in mind that this is not a released version and has not been extensively tested. Also, this code contains many changes from release 0.1.0 in addition to the one you requested. Some options may be different.

The newly added `--threads` option will be generally available with Shasta release 0.2.0.

**Comment by chklopp** [comment]
Thank you, I will test it.
