### ISSUE TITLE
Results availability

### ISSUE THREAD

**Issue by eleniadam** [chanzuckerberg/shasta#46]
Hello,

Is the assembly file of GM12878 available (results)?

Thank you,
Eleni

**Comment by paoloczi** [comment]
GM12878 (corresponding to HG001) was not sequenced and assembled as part of this paper. Perhaps you are thinking about the Jain _et al._ 2018 paper?

We are in the process of organizing assembly results in a publicly accessible online location and I will post that location once it is stable. If in the meantime you want results for a specific assembly I can give you a temporary location, but GM12878 in not in the list.

**Comment by paoloczi** [comment]
The assemblies from the paper are now available [here](https://s3-us-west-2.amazonaws.com/human-pangenomics/index.html?prefix=assemblies).

The reads are [here](https://s3-us-west-2.amazonaws.com/human-pangenomics/index.html).

**Comment by eleniadam** [comment]
@paoloczi, thank you very much!
