### ISSUE TITLE
low coverage data parameters

### ISSUE THREAD

**Issue by HMPNK** [chanzuckerberg/shasta#47]
Do you have any hints for optimizing SHASTA assembly on lower coverage data (20-30X)?

**Comment by paoloczi** [comment]
There was some discussion of this in issue #7, so I will be closing this one as a duplicate. The discussion in issue #7 included a suggested list of assembly parameters that should probably be scaled proportionally to coverage (see my Jun 3 post). So if you are at 20-30X you could halve the parameters in that list from their default value. 

If you have any results on this, please reopen issue #7 and post your findings there so others can benefit. Conceivably, we could add configuration files optimized for different values of coverage, or even functionality to scale parameters automatically. But to do that we first need to know what works!
