### ISSUE TITLE
Ambiguous runtime error; error during read

### ISSUE THREAD

**Issue by russellj7** [chanzuckerberg/shasta#48]
I'm attempting to run a human genome assembly using Shasta on MacOS with the default parameters. However, I quickly run into the error below. My FASTA file has one-line sequences and no blank lines, so I know that's not the issue. Any help is appreciated! Thanks!

```
Shasta Release 0.1.0

2019-Aug-21 08:37:31.773937 

This is the static executable for the Shasta assembler. It provides limited Shasta functionality at but has no dependencies and requires no installation.


Default values of assembly parameters are optimized for an assembly at coverage 60x. If your data have significantly different coverage, some changes in assembly parameters may be necessary to get good results.


For more information about the Shasta assembler, see

https://github.com/chanzuckerberg/shasta


Complete documentation for the latest version of Shasta is available here:

https://chanzuckerberg.github.io/shasta


Options in use:

Input FASTA files: linearized.fasta 

outputDirectory = ShastaRun

[Reads]

minReadLength = 10000

palindromicReads.maxSkip = 100

palindromicReads.maxMarkerFrequency = 10

palindromicReads.alignedFractionThreshold = 0.1

palindromicReads.nearDiagonalFractionThreshold = 0.1

palindromicReads.deltaThreshold = 100


[Kmers]

k = 10

probability = 0.1


[MinHash]

m = 4

hashFraction = 0.01

minHashIterationCount = 10

maxBucketSize = 10

minFrequency = 2


[Align]

maxSkip = 30

maxMarkerFrequency = 10

minAlignedMarkerCount = 100

maxTrim = 30


[ReadGraph]

maxAlignmentCount = 6

minComponentSize = 100

maxChimericReadDistance = 2


[MarkerGraph]

minCoverage = 10

maxCoverage = 100

lowCoverageThreshold = 0

highCoverageThreshold = 256

maxDistance = 30

edgeMarkerSkipThreshold = 100

pruneIterationCount = 6

simplifyMaxLength = 10,100,1000


[Assembly]

markerGraphEdgeLengthThresholdForConsensus = 1000

consensusCaller = SimpleConsensusCaller

useMarginPhase = False

storeCoverageData = False


Shasta Release 0.1.0

2019-Aug-21 08:37:31.775828 Loading reads from /Users/Desktop/linearized.fasta.

Input file block size: 2147483648 bytes.

Using 1 threads for reading and 36 threads for processing.

Input file size is 11368700965 bytes.

2019-Aug-21 08:37:31.807769 Reading block 0 2147483648, 2147483648 bytes.

2019-Aug-21 08:37:36.502823 Terminated after catching a runtime error exception:

Error during read.


```

**Comment by paoloczi** [comment]
To assemble a human genome you will need a machine with 1 or 2 TB of memory, depending on coverage. See [here](https://chanzuckerberg.github.io/shasta/Running.html#MemoryRequirements) for some guidelines about memory requirements. So you will not be able to run the human assembly on macOS. I suggest using AWS EC2 and instance type `x1.32xlarge` which has 1952 GB of memory and 128 virtual processors and is around $13 per hour. This what we have used for the [paper](https://www.biorxiv.org/content/10.1101/715722v1), and each human assembly completed in about 6 hours at a cost under $100.

The macOS version is not meant for large genome assembly. It can be used for testing and experimentation using bacterial or viral genomes, or for small subsets of larger genomes, with reads having been selected by other means.

See [here](https://chanzuckerberg.github.io/shasta/QuickStart.html#demo) (section entitled _Quick test and demonstration_) for a quick test on _E. coli_ that should run on your machine. You can use it to familiarize yourself with Shasta.

I agree the error message is too generic. Please try Release 0.2.0, which was just published yesterday, and that should give you a better error message. Please add a comment to this issue to confirm if the 0.2.0 error message is indeed more clear. But you will still not be able to run a human assembly on macOS.

**Comment by russellj7** [comment]
Thank you for such a detailed and quick reply! Okay, now I understand the error (based on memory requirements for a genome this size). My level of coverage is pretty low, around 2-3x on average. This might be in your paper you referenced, but why are the memory requirements so high for Shasta? For example, running the same dataset using Flye uses only ~ 130GB of RAM on MacOS. I'm guessing the answer has to do with differences in how Shasta and Flye operate.

I tried to generate the improved error message with Shasta 0.2.0 but the error message is identical to v.0.1.0. Please see below:

```
Shasta Release 0.2.0

2019-Aug-21 13:55:31.028926 

This is the static executable for the Shasta assembler. It provides limited Shasta functionality, at reduced performance when using the default options, but has no dependencies and requires no installation.


Default values of assembly parameters are optimized for an assembly at coverage 60x. If your data have significantly different coverage, some changes in assembly parameters may be necessary to get good results.


For more information about the Shasta assembler, see

https://github.com/chanzuckerberg/shasta


Complete documentation for the latest version of Shasta is available here:

https://chanzuckerberg.github.io/shasta


Options in use:

Input FASTA files: linearized.fasta 

assemblyDirectory = ShastaRun

[Reads]

minReadLength = 10000

palindromicReads.maxSkip = 100

palindromicReads.maxMarkerFrequency = 10

palindromicReads.alignedFractionThreshold = 0.1

palindromicReads.nearDiagonalFractionThreshold = 0.1

palindromicReads.deltaThreshold = 100


[Kmers]

k = 10

probability = 0.1


[MinHash]

m = 4

hashFraction = 0.01

minHashIterationCount = 10

maxBucketSize = 10

minFrequency = 2


[Align]

maxSkip = 30

maxTrim = 30

maxMarkerFrequency = 10

minAlignedMarkerCount = 100


[ReadGraph]

maxAlignmentCount = 6

minComponentSize = 100

maxChimericReadDistance = 2


[MarkerGraph]

minCoverage = 10

maxCoverage = 100

lowCoverageThreshold = 0

highCoverageThreshold = 256

maxDistance = 30

edgeMarkerSkipThreshold = 100

pruneIterationCount = 6

simplifyMaxLength = 10,100,1000


[Assembly]

strategy = 0

crossEdgeCoverageThreshold = 3

markerGraphEdgeLengthThresholdForConsensus = 1000

consensusCaller = Bayesian:guppy-2.3.5-a

useMarginPhase = False

storeCoverageData = False


The macOS version of the Shasta assembler runs at degraded performance.

Use Linux for full performance.

Therefore the results of this run should not be used

for benchmarking purposes.

Created a new assembly with page size 4096

This assembly will use 36 threads.

Setting up consensus caller Bayesian:guppy-2.3.5-a

Using predefined Bayesian consensus caller guppy-2.3.5-a

Bayesian consensus caller configuration name is Human guppy 2.3.5 chr1,chr2,chr3 GM24385 with hg38 priors and 1 pseudocounts 7-23-2019

2019-Aug-21 13:55:31.030823 Loading reads from /Users/erictriplett/Desktop/saliva-human/linearized.fasta.

Input file block size: 2147483648 bytes.

Using 1 threads for reading and 36 threads for processing.

Input file size is 11368700965 bytes.

2019-Aug-21 13:55:31.057433 Reading /Users/Desktop/linearized.fasta block 0 2147483648, 2147483648 bytes.

2019-Aug-21 13:55:35.889041 Terminated after catching a runtime error exception:

Error during read.
```

**Comment by paoloczi** [comment]
Shasta assembly parameters are optimized for coverage around 60x, which is what we had in the paper. At low coverage you will have to at least change some assembly parameters. I don't have good guidelines on this, but there is some discussion on a separate issue, issue #7. See there a list of assembly parameters there that should probably be scaled proportionally to coverage. If you have any findings on this, please append your comments at the end of issue #7 so what you find can be useful to others. 

However, even after changing assembly parameters, I doubt that you will be able to obtain good assembly results at that low coverage.

As explained in the paper, Shasta uses a lot more memory than alternative assemblers by design, and owes its high performance to that, at least in part. As a result, as shown in Fig. 2(f) of the [paper](https://www.biorxiv.org/content/10.1101/715722v1), Shasta is more than an order of magnitude faster than Flye. Large memory machines are easily available on the major cloud computing platforms at very reasonable cost - the compute cost per assembly is much lower than the sequencing costs incurred to generate the reads.

Even at that low coverage it is unlikely that you will be able to run on macOS. However the low coverage run should require much less than the 1-2 TB required at 60x. It is possible that 128 or 256 GB may be sufficient.

Thank you for posting the output of Shasta 0.2.0. The error message is clearly still insufficient. I will work on improving that.

**Comment by paoloczi** [comment]
I made the error message more informative (commit caf52e22bfc2920dd63daf962430f18e8721fec2). This fix will appear in the next release, or in builds done by users and including this commit.

For issues related to low coverage, please continue the discussion by appending to issue #7.

**Comment by paoloczi** [comment]
I labeled this as bug because the error message was insufficient.
