### ISSUE TITLE
Clean up of SimpleBayesianConsensusCaller code

### ISSUE THREAD

**Issue by paoloczi** [chanzuckerberg/shasta#5]
Some low priority clean up tasks in the `SimpleBayesianConsensusCaller` code:

* Remove compile warnings (some explicit conversions between integer types needed). 
* Harmonize naming conventions with the rest of the Shasta code.
* Remove Python-style `this->` in member functions.
* Pass vectors by reference.
* Make function `split` a static member of `SimpleBayesianConsensusCaller`.
* When errors occur, throw an an exception (`std::runtime_error`) instead of calling `exit`.
* Use `const` for variables that don't change (e. g. `int length = ...`).
* Don't use `BASE`, `BASE_INDEXES`, `base_keys`. Use class `Base` or `AlignedBase` instead.
* Use braces even for single-line code blocks in if/else (see the rest of the Shasta code for examples).

**Comment by paoloczi** [comment]
For spoa, rerunning InstallPrerequisitesUbuntu.sh should fix the issue. The error with std::accumulate was my fault - I did not see it before committing because I normally only compile on Ubuntu 16.04 and the error was only happening on 18.04. I fixed it last Friday.

I will take a look at the changes you made in your fork tomorrow.

**Comment by paoloczi** [comment]
I had a look at your changes and they look fine - when you like you can make a PR and I will merge it. Some comments:
* Please leave the file name as SimpleBayesianConsensusCaller.csv (without the "-1") suffix. I will add to the documentation instructions to copy to the run directory one of the sample files from the conf directory (of which there is currently only one, with the "-1" suffix) and rename it to SimpleBayesianConsensusCaller.csv.
* Sorry for getting your name wrong!
* I prefer integer types with explicit length (e. g uint32_t) to types like "unsigned int" whose meaning is platform dependent. But you don't need to adopt this preference in your code, as long as there are no compilation warnings.

**Comment by paoloczi** [comment]
The C++ standard only prescribes a minimum length for fundamental integer types. The actual length is left to be specified by the implementation. See [here](https://en.cppreference.com/w/cpp/language/types#Properties) for details. 64-bit Linux uses "data model" LP64.

Integer types with definite width are defined in C++ standard include file [\<cstdint\>](http://www.cplusplus.com/reference/cstdint/).

**Comment by rlorigro** [comment]
ok I opted to use uint32_t for all the vector iterators and uint16_t for anything regarding # of repeats (I assume we won't observe any homopolymers of length >65,535bp). Rewriting the types actually helped make the code much cleaner. 

I also rebased on your latest shasta and everything compiles now.

**Comment by paoloczi** [comment]
Assuming all compiler warnings are gone, if you like you can go ahead and create a PR and I will merge it. You can do the name changes in a separate PR.

**Comment by paoloczi** [comment]
Most of these items were addressed by PR#6. I will close this issue and create a new one with only the leftover items.
