### ISSUE TITLE
How to build the executable that is not static

### ISSUE THREAD

**Issue by hd00ljy** [chanzuckerberg/shasta#51]
Hello!

  I tried to build shasta from source to use these options
```
--Assembly.useMarginPhase
--Assembly.storeCoverageData
```
But I was not able to use it because the executable is static.

How should I build shasta so that I can use these options?

------------------------------------------------------------
Here are more details.

I built shasta according to the instruction in https://chanzuckerberg.github.io/shasta/BuildingFromSource.html
```
git clone https://github.com/chanzuckerberg/shasta.git
sudo shasta/scripts/InstallPrerequisites-Ubuntu.sh
mkdir shasta-build
cd shasta-build
cmake ../shasta
make all
make install
```

But I was not able to use those options with the executable 'shasta-build/shasta-install/bin/shasta', even though there was "shasta.so" in the same directory.

The error messages were like these
```
Shasta development build. This is not a released version.
2019-Aug-29 02:05:20.780316 Terminated after catching a runtime error exception:
Assembly.useMarginPhase is not supported by the Shasta static executable.
```
------------------------------------
with regards

Jinyoung

**Comment by paoloczi** [comment]
The integration of Shasta with MarginPolish is under development and is not functional. Even if you were to build a dynamically linked Shasta executable, it still would not support `--Assembly.useMarginPhase`.

In the [paper](https://www.biorxiv.org/content/biorxiv/early/2019/07/26/715722.full-text.pdf), we used MarginPolish as a separate tool after a Shasta assembly was completed. See the section entitled _MarginPolish_ in the  [supplementary materials](https://www.biorxiv.org/content/biorxiv/early/2019/07/26/715722/DC1/embed/media-1.pdf?download=true) of the paper for details on downloading and running MarginPolish.

Regarding option `--Assembly.storeCoverageData`, that is supported by the static executable in [Shasta Release 0.2.0](https://github.com/chanzuckerberg/shasta/releases/tag/0.2.0).
