### ISSUE TITLE
obtaining GFA output directly from the shasta executable

### ISSUE THREAD

**Issue by ekg** [chanzuckerberg/shasta#59]
This is a feature request. The prebuilt binaries are great, but there doesn't seem to be any way to use them to get GFA output. To do that, we need to build shasta on our target system to get the shared library that works as a python module, and this is somewhat involved without root. Would it be simple to add an option to shasta itself to provide GFA output of the raw assembly graph? Making the build simpler would be another way to make sure this is a feature that users in weird HPC environments can rely on.

**Comment by paoloczi** [comment]
The static executable already produces gfa output automatically for every assembly - you don't need to do anything special to get it. When an assembly completes, the assembly directory (this is the same directory that contains fasta assembly output in `Assembly.fasta`) also contains the following two files:

* `Assembly.gfa` contains the assembly in GFA 1.0 format.
* `Assembly-BothStrands.gfa`, also in GFA 1.0 format, contains a version of the assembly in which each segment appear twice, once for each strand orientation. Looking at this output is sometimes easier than using `Assembly.gfa`, particularly in intricate areas of the assembly graph. If you use Bandage to look at this file and turn on arrows, you will see that all links are consistent in direction - that is, they all connect the tail end of a segment to the beginning of other segments.

If you are not seeing these two files, it is possible that the process running your assembling was interrupted near completion, as writing these files takes just a few minutes for a human genome assembly.

**Comment by ekg** [comment]
Thanks!
