### ISSUE TITLE
Support for reads in compressed format (.gz and/or others)

### ISSUE THREAD

**Issue by paoloczi** [chanzuckerberg/shasta#62]
Shasta can load reads from uncompressed FASTA and FASTQ files. In some pipelines it is desirable to be able to read directly from compressed versions of the FASTA and FASTQ files. It is desirable to add Shasta support for reading directly from these compressed formats without requiring decompressing the files first. 

Compressed format of interest include `.gz` `.zip`, `.bz`, `.bz2`.

**Comment by ekg** [comment]
I've used [gzip_reader](https://github.com/gatoravi/gzip_reader.git) and been happy with it. I'd be curious if you find something that reads all of these compressed formats and presents a C++ interface.

IMO requiring uncompressed files is generally OK if you need to memory map them. Then you can avoid some copying, but it does place more burden on the user so the benefit needs to be significant.

**Comment by paoloczi** [comment]
I currently memory map the input files only temporarily, during read loading. The files are parsed, then closed and no longer referenced during the assembly. The read sequences are stored in binary format.  

For compressed files, the read loading process would be different.

A common use case is that the user has `fastq.gz` files. Currently they have to be uncompressed first which requires one extra pass to disk, which could be eliminated if we could read the file and uncompress on the fly. 

This is not high priority in my mind, but is desirable.

**Comment by DengHAU** [comment]
shasta-OldLinux-0.4.0 can't use compressed versions of the FASTA and FASTQ files.

**Comment by paoloczi** [comment]
Yes, currently no Shasta version can read compressed FASTA or FASTQ. You have to uncompress first.

Even if/when support for compressed files is added, decompression of `.gz` files is slow and cannot be parallelized, so you would probably still prefer to do the decompression on a cheaper machine than the one used for assembly.

**Comment by paoloczi** [comment]
I am leaning towards closing this issue, marking it as `wontfix`, and not implementing decompression in Shasta. My rationale is the following.

The most common format used for long term storage of reads is `.fastq.gz`. Unfortunately, for `.gz` files, decompression is intrinsically sequential and cannot be parallelized. Decompressing `.gz` files sequentially is very slow, and it does not make sense to tie up an expensive machine with 128  virtual processors to do sequential decompression. It is much more cost efficient to do decompression on a low end machine, then run the assembly on the high end machine using as input the decompressed file. 

The `pigz` library provides parallel compression to `.gz`, but decompression is still sequential, except for overlapping I/O. 

In the input is `.fastq.gz`, Shasta provides a script `FastqGzToFasta.py` that decompresses and converts to `.fasta` using a pipe, so there is a single pass to disk. The decompressed `.fasta` file usualy takes about the same amount of space as the compressed `.fastq.gz` file.

The issue with parallelism disappears with the `bz2` format, for which `pbzip2` can be used for highly parallel compression and decompression. However there are two issues with that:

* There is a tremendous inertia for people to continue to use the `.gz` format.
* Even if people convert to `.bz2` format, they have to use `pbzip2` when compressing, otherwise decompression remain sequential.

Please feel free to comment, criticize, correct errors, or provide additional information relevant to the above.
