### ISSUE TITLE
 High coverage assembly (was: SimpleBayesianConsensusCaller cleanup)

### ISSUE THREAD

**Issue by paoloczi** [chanzuckerberg/shasta#7]
Only the following low priority clean up tasks in the SimpleBayesianConsensusCaller code remain:

* Harmonize naming conventions with the rest of the Shasta code.
* Use braces even for single-line code blocks in if/else (see the rest of the Shasta code for examples).

**Comment by gitcruz** [comment]
Dear Chan Zuckerberg,

I have been testing SHASTA on some bacterial genomes using the available build release 0.10.1. However,this is suppose to work optimally with 60x coverage. In this particular case we are dealing with ~140x coverage data so I would like to adjust the assemblies to this coverage.  I have been checking the parameters and the website, but there's no clear information regarding this. Should I compile the program locally? Is there any guideline to adjust the build for >60x coverage?

Thanks in advance,
Fernando

**Comment by paoloczi** [comment]
Sorry Fernando - this project is at an early stage and for that reason the documentation is not very good. For the same reason, we have not yet had the time to experiment with higher coverage, as the emphasis of our current project is on human genomes. However, I would be happy to help you in the process. I suggest that you start by running with default parameters and let me know what you get. It is very possible that you will get a satisfactory assembly, but I cannot promise that. Depending on the results, I can suggest parameters to adjust.

To change an assembly parameter, you don't need to recompile or rebuild the code. You can use the executable distributed with release 0.1.0 specifying command line options to assign values to the non-default parameters. There is a long list of command line options controlling assembly parameters - you can get a list by invoking the executable with option `--help`. The meaning of some of them is described in the [documentation section on computational methods](https://chanzuckerberg.github.io/shasta/ComputationalMethods.html).

So, add a comment here when you have an initial assembly done with default parameters, and we can iterate from there.

**Comment by ramyavijayram** [comment]
Hi! Related to the question about high coverage genome assemblies, I have been attempting to assemble some simulated nanopore reads, with coverages ranging from very low (6) to very high (500-1000). For these simulated reads, so far the graphs generated have 0 vertices and edges, and the final assembly fasta file has 0 contigs. I have been trying to understand which parameters to change and what changes exactly to make, so that I get a proper graph. Can you please share some guidelines on this?

Thank you!

**Comment by paoloczi** [comment]
Here is a list of parameters for which the optimal value may be dependent on coverage:

`MinHash.maxBucketSize`
`MarkerGraph.minCoverage`
`MarkerGraph.maxCoverage`
`MarkerGraph.lowCoverageThreshold`
`MarkerGraph.highCoverageThreshold`
`MarkerGraph.edgeMarkerSkipThreshold`

As an initial attempt, I would suggest scaling these parameters proportionally to coverage, under the assumption that their default values are close to optimal at coverage 60x. Let me know what happens when you do that, and depending on that I can perhaps suggest further refinements. 

Ideally, it would be nice if you could share your findings with the Shasta community by posting here, because this is a topic of potential interest to others. If you find a good way to adjust parameters depending on coverage, we could either provide configuration files optimized for other coverage values, or even add an option to adjust the parameters dynamically.

**Comment by paoloczi** [comment]
I created a separate issue (#30) for the SimpleBayesianConsensusCaller cleanup.

**Comment by gitcruz** [comment]
Hi Paolo,

I tested with a 140x sample of Klebsiella pneumoniae, that is supposed to
have 1 main chromosome and 6 plasmids. The default parameters for 60x
resulted in an assembly with one main chromosome and 96 smaller chromosomes
(plasmids). Then I used MarkerGraph.minCoverage=30 and
MarkerGraph.minCoverage=260 and obtained 1 main chromosome and 4 others. I
am trying now with 25 and 255 to see if I can get closer to our unicycler
hybrid assembly results (main chrom and 6 plasmids).

So far I just played with these limits and let the others untouched.

Hope this helps. we can start building some guidelines to finetune
parameters around the nanopore sequencing coverage.

Best,
Fernando

**Comment by paoloczi** [comment]
Great, this is a nice start! Also, make sure so look at GFA output (`Assembly.gfa`), using [Bandage](https://rrwick.github.io/Bandage/) for example, to see the assembly connectivity. In your case you want disconnected segments, but the output may contain connectivity that may mimic your desired disconnected segments. For example, in your run with 96 smaller segments, gfa output may show that the 96 occur in connected components corresponding to your 6 plasmids.

**Comment by ramyavijayram** [comment]
Hey! So I tried modifying the mentioned parameters in approximately proportionately to the coverage; for very low coverages (3), it seems to give a very fragmented genome, with total length of contigs about three times the expected genome size. Is there something I can try to solve this problem, or some other issue with how I am running the assembler? Thank you!

**Comment by paoloczi** [comment]
I would be interested in knowing how well this recipe works for high coverage.

The test at coverage 3x is too stringent, as there is probably not enough information to assemble. It is generally believed that a strict minimum for _de novo_ assembly of reasonably quality is coverage 20x or so.

It may be fun to see if the contig breaks in the assembly correspond to regions where your simulator generated zero coverage (just because of the random placement of reads).

If you _really_ want to push coverage down (which however seems like a lost battle to me), I can suggest the following additional parameter changes:

*  Increase `--MinHash.minHashIterationCount` (for example from the default 10 to 20 or 50). This increases the probability that the LowHash algorithm will find most read overlaps.
* Decrease `--MinHash.minFrequency` from the default 2 to 1. This has the same effect as the previous item. This and the previous item have a performance cost.
* Decrease `--Align.minAlignedMarkerCount` from the default 100, for example to 50. This is the minimum number of aligned markers for an alignment between two reads to be used. However decreasing this parameter could also cause incorrect jumps in assembled sequence if your genome contains long repeats with high identity. This can also have a performance cost.

**Comment by paoloczi** [comment]
Since there have been no comments in a week, I will close this issue for now. Please feel free to reopen and comment if more information emerges. I would still be very interested in usable guidelines for parameter changes as a function of coverage, which I could add to the documentation or even possibly incorporate in the code.
