### ISSUE TITLE
Job killed at graph vertices

### ISSUE THREAD

**Issue by cuperusj** [chanzuckerberg/shasta#80]
Giving 256MB ram, for a expected ~600MB size genome, with pacbio reads shast keeps dying at Begin computing marker graph vertices. Perhaps you could give me insight into why that potentially could be? more memory? more processors (just 1 right now).

shasta --input milfoil1line.fa --Reads.minReadLength 2000 --Assembly.consensusCaller Modal --assemblyDirectory milfoil

**Comment by paoloczi** [comment]
This is a memory issue. Linux has the habit of killing jobs that cause memory shortage, and unfortunately I have no control over the message that gets written out in that case.

I recommend having 8 to 10 bytes of memory per input base. If your genome is 600 Mb and you are at 60x you have 36 Gb of coverage, and so the memory requirement estimated in this way would be 300-350 MB of memory. A machine with 512 MB will probably do the job.

If you were to use the more efficient options recommended for large runs `--memoryMode filesystem --memoryBacking 2M` you would get better error messages and also better performance, but these options require root access.

However, you will definitely need to increase the number of processors. With only one processor that assembly will take many days to run.

**Comment by paoloczi** [comment]
Given that nothing else came up, I am closing this. Feel free to create a new issue if other problems arise, or to reopen this one if the answer I gave above is not sufficiently helpful.
