### ISSUE TITLE
When will the next release be cut?

### ISSUE THREAD

**Issue by SHuang-Broad** [chanzuckerberg/shasta#86]
Hi,

I am trying out Shasta on a CCS data set and following the parameters suggested in #56.

However, the option `--MinHash.minBucketSize` is available only after the 0.2.0 release.
Building from source on my OS seems to be a non-trivial process as indicated in `docs/BuildingFromSource.html`.

Hence I am wondering when will the next release be, so that I can plan on what to do next.

Thank you!

Steve

**Comment by paoloczi** [comment]
The next Shasta release is imminent (probably this week or the next). However, to get this new functionality now you don't have to build the code yourself. You can download a current test build as described here. If you have any problems doing this let me know and I can help.

You can also keep this possibility in mind in the future, when new functionality appears in the repository but before a new release is created.

**Comment by paoloczi** [comment]
You may also want to consider experimenting with the new configuration files `shasta/conf/PacBio-CCS-Dec2019.conf` and  `shasta/conf/PacBio-CLR-Dec2019.conf`. 

To use one of these configuration files, you can use option `--config`, specifying the **absolute** path of the configuration you want to use. Also, keep in mind options you specify on the command line override values specified in a configuration file.
