### ISSUE TITLE
Support for MacOS 10.15.1

### ISSUE THREAD

**Issue by roshanahmed** [chanzuckerberg/shasta#94]
Need support for MacOS 10.15.1

**Comment by paoloczi** [comment]
I am certainly interested in providing up to date support for MacOS in Shasta. To help me with that, could you please post the error messages you get when you attempt to use Shasta release 0.4.0 on your system?

**Comment by paoloczi** [comment]
I added a MacOs 10.15 build to the Shasta automated build and test workflow, and everything worked without requiring any code changes. The test workflow includes running a small assembly. Please download the test build and verify that it works for you. You can download it from [here](https://github.com/chanzuckerberg/shasta/suites/424629694/artifacts/1396955). You will have to unzip it and make it executable before you can run it.

For the future, directions to download test builds are available [here](https://chanzuckerberg.github.io/shasta/BuildingFromSource.html#DownloadTestBuild). You can use this at any time to download the most recent test build containing the latest features available in the GitHub repository but not yet in a released Shasta version.

Once you confirm that the MacOS 10.15 test build works for you I will close this issue.

**Comment by Hikoyu** [comment]
I can rebuild shasta-0.4.0 (CPU only) on macOS 10.14.
Editing `staticExecutable/CMakeLists.txt` is needed if `spoa` library is NOT installed to `/usr/local`.

**Comment by paoloczi** [comment]
There is a script `shasta/scripts/InstallPrerequisites-macOS.sh` that installs spoa and other Shasta prerequisites for macOS. This works both for macOS 10.14 and 10.15. It is used by the Shasta automated build using GitHub Actions (see `shasta/.github/workflows/Build.yml`).

The test build now builds both for 10.14 and 10.15, and the next release will also include both.

**Comment by paoloczi** [comment]
@roshanahmed when you have a chance please confirm that you can run the Shasta executable for macOS 10.15, using the directions above (3 comments up) to download it. You don't have to build it yourself. Once you confirm that it works for you I will close this issue.

**Comment by paoloczi** [comment]
Since there were no comments, I am closing this issue, but feel free to reopen it or comment.

The macOS 10.15 version of Shasta is now automatically built with each test build and will be included in the next release. You can to use the directions  [here](https://chanzuckerberg.github.io/shasta/BuildingFromSource.html#DownloadTestBuild) to download a current test build.
