### ISSUE TITLE
error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.

### ISSUE THREAD

**Issue by NGLJ** [chanzuckerberg/shasta#96]
HI,
We are trying your software,but when we build it with GPU,An error occurred:

[ 32%] Building CUDA object staticExecutableGpu/CMakeFiles/gpuLib.dir/__/src/gpu/GPU.cu.o
In file included from /usr/include/c++/5/mutex:35:0,
                 from /mnt/data1/lixinyue/docker/test_xfy/shasta/shasta/shasta-0.4.0/src/gpu/GPU.cu:8:
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \
  ^
staticExecutableGpu/CMakeFiles/gpuLib.dir/build.make:62: recipe for target 'staticExecutableGpu/CMakeFiles/gpuLib.dir/__/src/gpu/GPU.cu.o' failed
make[2]: *** [staticExecutableGpu/CMakeFiles/gpuLib.dir/__/src/gpu/GPU.cu.o] Error 1
CMakeFiles/Makefile2:150: recipe for target 'staticExecutableGpu/CMakeFiles/gpuLib.dir/all' failed
make[1]: *** [staticExecutableGpu/CMakeFiles/gpuLib.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

Config:
g++ 5.4 or 4.9
cuda 10.0
ubuntu16.04

best,
XFY

**Comment by paoloczi** [comment]
The GPU functionality is only supported on Ubuntu 18.04.
